### PR TITLE
Make svcat broker commands with --wait support namespaced brokers

### LINKED ISSUE #2593: broker --wait flag doesn't work for namespaced brokers

### PR DESCRIPTION
**Pull request by jberkhahn**
This PR is a 
 - [x] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
svcat broker commands with the --wait flag now wait for namespaced brokers

**Which issue(s) this PR fixes** 
fixes #2593

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

File: pkg/svcat/service-catalog/broker.go [hunk 1]
```diff
@@ -310,14 +310,14 @@ func (sdk *SDK) Sync(name string, scopeOpts ScopeOptions, retries int) error {
...
 // WaitForBroker waits for the specified broker to be Ready or Failed
-func (sdk *SDK) WaitForBroker(name string, interval time.Duration, timeout *time.Duration) (broker Broker, err error) {
+func (sdk *SDK) WaitForBroker(name string, opts *ScopeOptions, interval time.Duration, timeout *time.Duration) (broker Broker, err error) {
 	if timeout == nil {
 		notimeout := time.Duration(math.MaxInt64)
 		timeout = &notimeout
 	}
 	err = wait.PollImmediate(interval, *timeout,
 		func() (bool, error) {
-			broker, err = sdk.retrieveBroker(name)
```
Comment (MHBauer) [inline pkg/svcat/service-catalog/broker.go]: this is really the key shift, from some internal name function to the name/id with scoping options added. both already existed and I guess continue to exist until some later refactor.
