### PR TITLE
delay between provisioning retries

### LINKED ISSUE #2025: Provide delay after performing orphan mitigation when Service Instance was failed
Hello,
We wrote about our issue in #2006. It's about infinite loop when Service Instance provision fails, e.g. when some condition from our business logic wasn't fulfilled.

The loop looks like this: 
```
start provisioning -> fail, requires orphan mitigation -> perform orphan mitigation 
-> start provisioning -> …
```

In the issue #2006, @nilebox suggested using `reconciliation-retry-duration` flag, but it didn't help us. 
It defines how much time does the Service Catalog have to ask for the last operation.
In our case, each step is another operation so it won't work.
We need a similar solution but for the whole loop showed above.

These are the logs from the controller-manager when I started to provision a Service Instance which fails: 
```
08:30:35.840997       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision request for ServiceInstance in-flight to Broker
08:30:36.044199       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance is being provisioned asynchronously
08:30:36.053577       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2317", FieldPath:""}): type: 'Normal' reason: 'Provisioning' The instance is being provisioned asynchronously
08:30:37.055727       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:37.055791       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:37.055872       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource
08:30:37.056042       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2318", FieldPath:""}): type: 'Warning' reason: 'ProvisionCallFailed' Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:37.056060       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2318", FieldPath:""}): type: 'Warning' reason: 'StartingInstanceOrphanMitigation' The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource
08:30:37.248135       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance is being deprovisioned asynchronously
08:30:37.258984       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2319", FieldPath:""}): type: 'Normal' reason: 'Deprovisioning' The instance is being deprovisioned asynchronously
08:30:39.067922       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Orphan mitigation was completed successfully
08:30:39.074778       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2320", FieldPath:""}): type: 'Normal' reason: 'OrphanMitigationSuccessful' Orphan mitigation was completed successfully
08:30:39.240388       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision request for ServiceInstance in-flight to Broker
08:30:39.445902       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance is being provisioned asynchronously
08:30:39.451549       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2322", FieldPath:""}): type: 'Normal' reason: 'Provisioning' The instance is being provisioned asynchronously
08:30:40.454954       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:40.455026       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:40.455087       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource
08:30:40.455744       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2323", FieldPath:""}): type: 'Warning' reason: 'ProvisionCallFailed' Provision call failed: Forbidden provisioning instance [3edc6a28-5363-11e8-83ff-0242ac110022] for remote environment [id: ac031e8c-9aa4-4cb7-8999-0d358726ffaa] in namespace: [production]. Reason: [already activated]
08:30:40.455777       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2323", FieldPath:""}): type: 'Warning' reason: 'StartingInstanceOrphanMitigation' The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource
08:30:40.642871       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": The instance is being deprovisioned asynchronously
08:30:40.654647       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2324", FieldPath:""}): type: 'Normal' reason: 'Deprovisioning' The instance is being deprovisioned asynchronously
08:30:40.765473       1 controller_manager.go:414] Health-checking connection with service-catalog API server
08:30:42.471662       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Orphan mitigation was completed successfully
08:30:42.482370       1 event.go:218] Event(v1.ObjectReference{Kind:"ServiceInstance", Namespace:"production", Name:"promotions-service1", UID:"3edc6ed3-5363-11e8-83ff-0242ac110022", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"2325", FieldPath:""}): type: 'Normal' reason: 'OrphanMitigationSuccessful' Orphan mitigation was completed successfully
08:30:42.639328       1 controller_instance.go:1143] ServiceInstance "production/promotions-service1": Provision request for ServiceInstance in-flight to Broker
```
and so on forever..

As you can see, the Service Catalog continuously spams our broker with provision and deprovision requests without any delay or maxRetries (or maxRetryDuration) amount.

We would expect a flow like this: 
```
(start provisioning -> fail, requires orphan mitigation -> perform orphan mitigation ->  exponential delay) x maxRetries
```
Our idea is to provide an exponential delay after performing an orphan mitigation to avoid spamming the brokers.
Let us know what do you think about it :)
Also let us know if you need the code snippets from the Service Catalog where the whole cycle is executed.
Thank you in advance.

### PR DESCRIPTION
**Pull request by jboyd01**
fixes #2025 - at least it prevents Controller from blasting Brokers with constant provision retry/orphan mitigation loop.

In addition to #2025, see #2076 for additional details on problems with the instance reconciliation.  This PR is a near term band-aid to prevent pain at the brokers.

A new in memory list of instances with provision retry times provides a delay to prevent a tight provision/provision-failure/orphan mitigation loop that pounds brokers without pause when provisioning ends with non-terminal failure.

This short term fix adds the retryQueue where we introduce additional delay on top of what the reconciler loop was originally doing.  Before doing a broker operation (Provision or Update) we check the backoffBeforeRetrying and retryTime maps to see if we should first delay.  If the instance has an entry in backoffBeforeRetrying that indicates the operation previously failed and we need to get a new exponential backoff delay from the RateLimter.  This is calculated and a new time is set in the retryTime and then then the instance is put back into the main worker queue with an AddAfter(time) which causes the worker to reprocess after the delay.  On this next pass, verification is done to ensure the time delay has expired and we then set the dirty bit in the backoffBeforeRetrying in anticipation of another failure.  If the operation is successful, the entries will be cleared from the retryQueue.  A failure runs through the process again.  A background tasks periodically purges old  entries from retryQueue.

The main point above is that all the backoff processing happens just before we execute the broker operation.  There are a lot of edge cases and post error processing that otherwise makes it difficult to instrument the backoff properly in all the necessary places.  This is a best effort band aid, a temporary work around until the overall reconcilation flow can be reworked properly (issue #2076).

We do not do additional backoff for Deprovisioning (regular or Orphan Mitigation) as the OM status handling is embedded with in the delete and its difficult to be certain if a delete is part of OM and ensuring we don't clear out overall backoff if there are failures and then success within OM.

Binding Reconcilation likely has the exact same issues.

### CODE REVIEW

**Comment by jboyd01** [comment]
@luksa, @kibbles-n-bytes could you review?  Travis error is with building docsite, unrelated failure that I'm attempting to address, but this PR is ready to go I believe.

File: pkg/controller/controller_instance.go [hunk 1]
```diff
@@ -329,6 +349,68 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+// setNextProvisionRetryTime adds the instance name to the map recording the next earliest time to
+// retry provisioning
+func (c *controller) setNextProvisionRetryTime(instance *v1beta1.ServiceInstance) {
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf("Couldn't get key for object %+v: %v", instance, err)
+		return
+	}
+	c.provisionRetryQueue.mutex.Lock()
+	c.provisionRetryQueue.retryTime[key] = time.Now().Add(c.provisionRetryQueue.retryInterval)
```
Comment (luksa) [inline pkg/controller/controller_instance.go]: Can you take a look at `NewItemExponentialFailureRateLimiter()` in `github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/util/workqueue/default_rate_limiters.go` ? 

I think adding a nice exponential backoff instead of a constant delay should be fairly simple. The rate limiter has a `When()` method you can call to get the next time. 

But I haven't really looked at the rate limiters closely. So I may be wrong :)

File: pkg/controller/controller_instance.go [hunk 2]
```diff
@@ -339,6 +421,18 @@ func (c *controller) reconcileServiceInstanceAdd(instance *v1beta1.ServiceInstan
 		return nil
 	}
 
+	// don't DOS the broker.  If we already did a provision attemp that ended with a non-terminal
```
Comment (luksa) [inline pkg/controller/controller_instance.go]: s/attemp/attempt/

File: pkg/controller/controller_instance.go [hunk 3]
```diff
@@ -99,8 +111,16 @@ func (c *controller) instanceAdd(obj interface{}) {
 		glog.Errorf("Couldn't get key for object %+v: %v", obj, err)
 		return
 	}
+	c.instanceQueue.AddRateLimited(key)
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: I'm fine with reverting this so it isn't rate limited, I did it per https://github.com/kubernetes-incubator/service-catalog/issues/2025#issuecomment-389620752, but I do want to note that even if we do a backoff/retry the max # of retry times (15), they are all completed in under 3 minutes.  Check out the backoff times:  https://github.com/kubernetes-incubator/service-catalog/blob/6a693a7661654faa2dffa2d50d44f8d676207b7c/pkg/controller/controller.go#L57

File: cmd/controller-manager/app/options/options.go [hunk 4]
```diff
@@ -60,6 +60,7 @@ const (
 	defaultLeaderElectionNamespace                = "kube-system"
 	defaultReconciliationRetryDuration            = 7 * 24 * time.Hour
 	defaultOperationPollingMaximumBackoffDuration = 20 * time.Minute
+	defaultProvisioningRetryInterval              = 5 * time.Minute
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply cmd/controller-manager/app/options/options.go]: It's way too long when you have a single failure, but when the broker is in a bad state and just sits there returning a retry-able error it's pretty frequent.  Optimally we'd do a set of quick retries and then fall back to every 5 or 10 minutes, but I don't think the effort for that is worth it as we need to rework this anyway (#2076).  Suggestions on a better backoff?  Once a minute?  Note that this is overridable with the flag --provision-retry-interval

File: pkg/controller/controller_instance.go (hunk 1 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: An exponential backoff is ideal, it is what we were supposed to be doing here, but we constantly reset the notion of failure/success when we do status updates or complete the orphan mitigation and we never quit after max retries, it just restarts all over.

To use exponential backoff we need to maintain more state, including the # of retries.

Ideally we would have a queue much like today that has very short backoff/retry for kube reconciliation, but we probably need another queue that is for remote broker operations that has a larger backoff.  I 100% agree that exponential backoff is the right fix, but its going to take a large rework.  The only goal of this PR is to stop us from pounding on the broker.

File: pkg/controller/controller_instance.go (hunk 2 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Thanks for the review @luksa, I've updated the typo and incorrect comment, I'm open to suggestions on a better retry interval.  I'd be ok with 60 seconds vs 5 minutes.  In discussion with @pmorie we were thinking 20 minutes, but that really focuses on constant failure cases.

File: pkg/controller/controller_instance.go (hunk 1 above)
Comment (luksa) [reply pkg/controller/controller_instance.go]: No, I meant just create a new rate limiter instead of the `retryTime` map. The rate limiter keeps track of everything. All you need to do is call `rateLimiter.When(instance)` here and it'll keep track of the individual delays for each ServiceInstance.

Comment (jboyd01) [reply pkg/controller/controller_instance.go]: I see what you are saying Marko, great idea.  I think I'll have to keep the `retryMap` in addition to adding the `rateLimter`.  The `rateLimiter` doesn't have support for checking if an item is in queue and getting the next execution time.  But I really like the idea of exponential backoff.

File: test/util/util.go [hunk 5]
```diff
@@ -184,6 +190,16 @@ func WaitForInstanceCondition(client v1beta1servicecatalog.ServicecatalogV1beta1
...
 
+// PrintInstance logs the instance details
+func PrintInstance(client v1beta1servicecatalog.ServicecatalogV1beta1Interface, namespace, name string) {
+	instance, err := client.ServiceInstances(namespace).Get(name, metav1.GetOptions{})
+	if nil != err {
+		glog.Infof("Error getting Instance %v/%v: %v", namespace, name, err)
+		return
+	}
+	glog.Infof("Instance %v/%v: %+v", namespace, name, instance)
+}
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply test/util/util.go]: Thanks @luksa, I've reverted back to non rate limited add and corrected  the other two issues.

**Comment by luksa** [comment]
LGTM

I'd /lgtm but I'm not in the kubernetes-incubator org yet. Hopefully they'll add me today.

**Comment by jboyd01** [comment]
hmm...  It appears changing the ```c.instanceQueue.AddRateLimited(key)``` back to ```c.instanceQueue.Add(key)``` in InstanceAdd() breaks integration tests.  Even greatly increasing overall wait timeout still fails.  Investigating.

**Comment by jboyd01** [comment]
@kibbles-n-bytes, @nilebox could you please review?

File: pkg/controller/controller_instance.go [hunk 6]
```diff
@@ -89,8 +91,22 @@ const (
 	startingInstanceOrphanMitigationMessage string = "The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource"
 
 	clusterIdentifierKey string = "clusterid"
+
+	minBrokerProvisioningRetryDelay time.Duration = time.Second * 1
+	maxBrokerProvisioningRetryDelay time.Duration = time.Minute * 20
 )
 
+type retryQueue struct {
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: this strikes me as the wrong place to define this, or it needs a better name, as it seems very provision+instance specific.

File: pkg/controller/controller.go [hunk 7]
```diff
@@ -221,7 +222,8 @@ type controller struct {
 	// clusterIDLock protects access to clusterID between the
 	// monitor writing the value from the configmap, and any
 	// readers passing the clusterID to a broker.
-	clusterIDLock sync.RWMutex
+	clusterIDLock       sync.RWMutex
+	provisionRetryQueue retryQueue
```
Comment (MHBauer) [inline pkg/controller/controller.go]: new struct defined in controller_instance.

File: pkg/controller/controller_instance.go (hunk 6 above)
Comment (MHBauer) [reply pkg/controller/controller_instance.go]: granted I'm not familiar with the existing queues, but is there a reason to avoid using some version of  "k8s.io/client-go/util/workqueue" ?

File: pkg/controller/controller.go [hunk 8]
```diff
@@ -167,7 +167,8 @@ func NewController(
 		//DeleteFunc: controller.servicePlanDelete,
 		//})
 	}
-
+	controller.provisionRetryQueue.retryTime = make(map[string]time.Time)
+	controller.provisionRetryQueue.rateLimiter = workqueue.NewItemExponentialFailureRateLimiter(minBrokerProvisioningRetryDelay, maxBrokerProvisioningRetryDelay)
```
Comment (MHBauer) [inline pkg/controller/controller.go]: the base `controller.provisionRetryQueue` is just the empty struct from basic object instantiation, right? Nothing extra we need to do before we start touching it's pieces? 

The OO/Java guy in me wants this done in a constructor of retryQueue, but we're in a controntroller constructor for an internal private object, so I think we're fine for now.

Comment (MHBauer) [reply pkg/controller/controller.go]: I don't like the constants being defined in the other file.

File: pkg/controller/controller_instance.go [hunk 9]
```diff
@@ -89,8 +91,22 @@ const (
...
+	mutex sync.RWMutex // lock to be used with retryTime
+
+	// If instance has an entry in map, this is the earliest time at which a
+	// provision reattempt shoud be made to ensure we don't overwhelm broker
+	// with repeated requests.
+	retryTime        map[string]time.Time
+	queueLastCleaned time.Time
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: needs comment.

File: pkg/controller/controller_instance.go [hunk 10]
```diff
@@ -329,6 +353,76 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+		return t.Sub(now)
+	}
+	return 0
+}
+
+// purgeExpiredRetryEntries periodically clears entries from the map that have an expired
+// retry time.
+func (c *controller) purgeExpiredRetryEntries() {
+	now := time.Now()
+	if now.Before(c.provisionRetryQueue.queueLastCleaned.Add(maxBrokerProvisioningRetryDelay * 2)) {
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: why `* 2` ?

File: pkg/controller/controller_instance.go [hunk 11]
```diff
@@ -329,6 +353,76 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+		return
+	}
+	c.provisionRetryQueue.mutex.Lock()
+	defer c.provisionRetryQueue.mutex.Unlock()
+
+	// Ensure we only purge items that aren't being acted on by retries, this shouldn't
+	// have any work to do but we want to be certain this queue doesn't get overly large.
+	overDue := now.Add(-maxBrokerProvisioningRetryDelay)
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: add negative seems weird.

File: pkg/controller/controller_instance.go [hunk 12]
```diff
@@ -329,6 +353,76 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	for k := range c.provisionRetryQueue.retryTime {
+		if c.provisionRetryQueue.retryTime[k].Before(overDue) {
+			glog.V(5).Infof("removed %s from provisionRetry map which had retry time of %v", k, c.provisionRetryQueue.retryTime[k])
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: is there a log message before this to let us know what time "now" is so that we can see how backed off this is?

File: pkg/controller/controller_instance.go [hunk 13]
```diff
@@ -329,6 +353,76 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+			delete(c.provisionRetryQueue.retryTime, k)
+			c.provisionRetryQueue.rateLimiter.Forget(k)
+		}
+	}
+	glog.V(5).Infof("purged expired entries, provisionRetry queue length is %v", len(c.provisionRetryQueue.retryTime))
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: before and after count? or how many were purged?

File: pkg/controller/controller_instance.go [hunk 14]
```diff
@@ -339,6 +433,18 @@ func (c *controller) reconcileServiceInstanceAdd(instance *v1beta1.ServiceInstan
 		return nil
 	}
 
+	// don't DOS the broker.  If we already did a provision attempt that ended with a non-terminal
+	// error then we set a next retry time.  Observe that.
```
Comment (MHBauer) [inline pkg/controller/controller_instance.go]: more context for "observe that".

File: pkg/controller/controller_instance.go (hunk 6 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: This is very instance & provision oriented.  This isn't meant to be long term - it's a long read, but #2076 discusses many of the existing issues we're seeing in here.  The instance controller really needs a major refactoring - I don't picture this new provisionRetryQueue code being part of it.  This is purely to plug a hole specific instance provisioning retry.

File: pkg/controller/controller.go (hunk 8 above)
Comment (jboyd01) [reply pkg/controller/controller.go]: Right, I hear you.  But this is very specific to the instance controller, I originally had it all contained there with initialization in an init method, but I think this is clearer.

File: pkg/controller/controller_instance.go (hunk 10 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: I don't want to prematurely remove any entries, but I agree * 2 is arbitrary without comments.  I'll update it.

File: pkg/controller/controller_instance.go (hunk 12 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Initial calculation is is done ihere and logged: https://github.com/kubernetes-incubator/service-catalog/blob/cb9ae55ef70a75e26f4344f64c5a8c9639e0a5d3/pkg/controller/controller_instance.go#L367

when we backoff vs doing a regularly scheduled provision attempt we log it as well:  https://github.com/kubernetes-incubator/service-catalog/blob/cb9ae55ef70a75e26f4344f64c5a8c9639e0a5d3/pkg/controller/controller_instance.go#L439

File: pkg/controller/controller_instance.go (hunk 13 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: My real concern was ensuring the map didn't grow - I'll add additional logging indicating how many remain in the map.

File: pkg/controller/controller_instance.go (hunk 14 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: I'll update.  @MHBauer thanks for the review and comments, I'll update accordingly.

File: pkg/controller/controller_instance.go (hunk 11 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Yeah, but I have a duration and Time.Sub() takes another Time type.  Adding a negative duration is the prescribed way AFAIK.

File: pkg/controller/controller.go (hunk 8 above)
Comment (MHBauer) [reply pkg/controller/controller.go]: please no inits

File: pkg/controller/controller_instance.go (hunk 6 above)
Comment (MHBauer) [reply pkg/controller/controller_instance.go]: okay, thanks

File: pkg/controller/controller_instance.go [hunk 15]
```diff
@@ -389,23 +389,33 @@ func (c *controller) getDelayForProvisionRetry(instance *v1beta1.ServiceInstance
...
 	}
 	c.provisionRetryQueue.mutex.Lock()
 	defer c.provisionRetryQueue.mutex.Unlock()
 
-	// Ensure we only purge items that aren't being acted on by retries, this shouldn't
-	// have any work to do but we want to be certain this queue doesn't get overly large.
+	// Ensure we only purge items that aren't being acted on by retries, this
+	// shouldn't have much work to do but we want to be certain this queue
+	// doesn't get overly large. Entries are removed one by one when deleted
+	// (not orphan mitigation)of successfully provisioned, this function ensures
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: you got it, thanks, fixed.  And to your comment below - yes, as I updated this comment I realized I wasn't thinking of the happy-path... I updated the provision success code to remove the entry from the map and verified the change.

File: pkg/controller/controller_instance.go [hunk 16]
```diff
@@ -329,6 +353,86 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	duration := c.provisionRetryQueue.rateLimiter.When(key)
+	c.provisionRetryQueue.mutex.Lock()
+	c.provisionRetryQueue.retryTime[key] = time.Now().Add(duration)
+	glog.V(4).Infof("provisionRetry for %s after %v", key, duration)
+	c.provisionRetryQueue.mutex.Unlock()
+}
+
+//  delayProvisionRetry returns a duration which should be observed before attempting to provision
+func (c *controller) getDelayForProvisionRetry(instance *v1beta1.ServiceInstance) time.Duration {
+	c.purgeExpiredRetryEntries()
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: `get...` in the method name suggests that this method should not have any side effects.
I would prefer to explicitly invoke `purgeExpiredRetryEntries` when needed, rather then doing it here hidden from the user.

File: pkg/controller/controller_instance.go [hunk 17]
```diff
@@ -329,6 +353,86 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf("Couldn't get key for object %+v: %v", instance, err)
+		return
+	}
+	duration := c.provisionRetryQueue.rateLimiter.When(key)
+	c.provisionRetryQueue.mutex.Lock()
+	c.provisionRetryQueue.retryTime[key] = time.Now().Add(duration)
+	glog.V(4).Infof("provisionRetry for %s after %v", key, duration)
+	c.provisionRetryQueue.mutex.Unlock()
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: do `defer c.provisionRetryQueue.mutex.Unlock()` right after acquiring lock instead to be safe?

File: pkg/controller/controller_instance.go [hunk 18]
```diff
@@ -329,6 +353,86 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf("Couldn't get key for object %+v: %v", instance, err)
+		return 0
+	}
+	c.provisionRetryQueue.mutex.RLock()
+	defer c.provisionRetryQueue.mutex.RUnlock()
+	now := time.Now()
+	if t := c.provisionRetryQueue.retryTime[key]; t.After(now) {
+		return t.Sub(now)
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: There is still a small chance for this value to be negative (between `t.After()` and `t.Sub()` some time has passed).
To be safe, this whole block can be rewritten to:
```go
t := c.provisionRetryQueue.retryTime[key]
delay := t.Sub(now)
if delay < 0 {
  return 0
}
return delay
```

File: pkg/controller/controller_instance.go [hunk 19]
```diff
@@ -329,6 +353,86 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	c.purgeExpiredRetryEntries()
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf("Couldn't get key for object %+v: %v", instance, err)
+		return 0
+	}
+	c.provisionRetryQueue.mutex.RLock()
+	defer c.provisionRetryQueue.mutex.RUnlock()
+	now := time.Now()
+	if t := c.provisionRetryQueue.retryTime[key]; t.After(now) {
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: we should probably check for the key to be present in the map? i.e. `if t, ok := ...; ok { ... }`

Comment (nilebox) [reply pkg/controller/controller_instance.go]: ah, it will lead to `t` being equal to `0` in that case, fine.

File: pkg/controller/controller_instance.go [hunk 20]
```diff
@@ -329,6 +353,86 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	// doesn't get overly large. Entries are removed one by one when deleted
+	// (not orphan mitigation) or successfully provisioned, this function ensures
+	// all others get purged eventually.  Due to queues and potential delays,
+	// only remove entries that are at least maxBrokerProvisioningRetryDelay
+	// past next retry time to ensure entries are not prematurely removed
+	overDue := now.Add(-maxBrokerProvisioningRetryDelay)
+	purgedEntries := 0
+	for k := range c.provisionRetryQueue.retryTime {
+		if c.provisionRetryQueue.retryTime[k].Before(overDue) {
+			glog.V(5).Infof("removed %s from provisionRetry map which had retry time of %v", k, c.provisionRetryQueue.retryTime[k])
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: I prefer to cache the value in the var if it's being used twice (`c.provisionRetryQueue.retryTime[k]`).

File: pkg/controller/controller_instance.go [hunk 21]
```diff
@@ -339,6 +443,18 @@ func (c *controller) reconcileServiceInstanceAdd(instance *v1beta1.ServiceInstan
 		return nil
 	}
 
+	// don't DOS the broker.  If we already did a provision attempt that ended with a non-terminal
+	// error then we set a next retry time.
+	if delay := c.getDelayForProvisionRetry(instance); delay > 0 {
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: What if the instance spec was updated? have we purged the item from the `provisionRetryQueue` by this time?
We should reset the backoff when we start a new operation with generation incremented?

File: pkg/controller/controller_instance.go [hunk 22]
```diff
@@ -1685,7 +1809,7 @@ func (c *controller) processProvisionSuccess(instance *v1beta1.ServiceInstance,
 	if _, err := c.updateServiceInstanceStatus(instance); err != nil {
 		return err
 	}
-
+	c.removeInstanceFromRetryMap(instance)
```
[the remark this answers is not in the document]
Comment (nilebox) [reply pkg/controller/controller_instance.go]: I think there should also be a case when we hit a "terminal" error for a particular generation (e.g. `400 Bad Request`)  and won't retry until the spec is updated. We should invoke `c.removeInstanceFromRetryMap(instance)` in that case as well. Otherwise, when the spec will be updated, we will still retry with accumulated delay...

[the remark this answers is not in the document]
Comment (nilebox) [reply pkg/controller/controller_instance.go]: I'm talking about `processTerminalProvisionFailure` (https://github.com/kubernetes-incubator/service-catalog/blob/491f227a4fc7453917e347ccc957da9a312a4774/pkg/controller/controller_instance.go#L1695:22) and `processTerminalUpdateServiceInstanceFailure` (https://github.com/kubernetes-incubator/service-catalog/blob/491f227a4fc7453917e347ccc957da9a312a4774/pkg/controller/controller_instance.go#L1801)

File: pkg/controller/controller_instance.go (hunk 17 above)
Comment (pmorie) [reply pkg/controller/controller_instance.go]: Agree with @nilebox that defer should be used here to ensure the lock is released.

File: pkg/controller/controller_instance.go (hunk 18 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: If I was using time.Now() I'd agree, but these variables are not going to change between checking and subtracting.

File: pkg/controller/controller_instance.go (hunk 21 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: good point.  I've updated the map to use the instance with the generation appended now.  This ensures if the instance is updated the backoff will be reset.

File: pkg/controller/controller_instance.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Agreed, good catch.

File: pkg/controller/controller_instance.go (hunk 18 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: ah true.

File: pkg/controller/controller_instance.go [hunk 23]
```diff
@@ -1696,6 +1844,7 @@ func (c *controller) processTerminalProvisionFailure(instance *v1beta1.ServiceIn
 	if failedCond == nil {
 		return fmt.Errorf("failedCond must not be nil")
 	}
+	c.removeInstanceFromRetryMap(instance)
 	return c.processProvisionFailure(instance, readyCond, failedCond, shouldMitigateOrphan)
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: Here and in other places: there is a chance that we will fail to update the status inside `processProvisionFailure`, but we have already removed instance from retry map. Which means that operation will be retried without backoff.
Probably fine, given that the probability of this seems low, and it won't break anything.

File: pkg/controller/controller_instance.go [hunk 24]
```diff
@@ -1721,6 +1870,10 @@ func (c *controller) processProvisionFailure(instance *v1beta1.ServiceInstance,
 		errorMessage = fmt.Errorf(readyCond.Message)
 	}
 
+	// assume a provision retry will happen, set a not-before time so we don't pound the Broker
+	// in a constant try to provision/fail/orphan mitigation/repeat loop.
+	c.setNextOperationRetryTime(instance)
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: This is only needed for non-terminal errors. For terminal errors you have just removed instance from the retry map in `processTerminalProvisionFailure`.
So the proper place to put this is into the "non-terminal" condition block below: https://github.com/kubernetes-incubator/service-catalog/blob/3837abf27fe5d9b090a7d530a81d6cebc634a79e/pkg/controller/controller_instance.go#L1747-L1752

File: pkg/controller/controller_instance.go [hunk 25]
```diff
@@ -1696,6 +1844,7 @@ func (c *controller) processTerminalProvisionFailure(instance *v1beta1.ServiceIn
 	if failedCond == nil {
 		return fmt.Errorf("failedCond must not be nil")
 	}
+	c.removeInstanceFromRetryMap(instance)
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: We should probably remove instance if `!shouldMitigateOrphan`. I guess we could just move this line inside `processProvisionFailure` under condition
https://github.com/kubernetes-incubator/service-catalog/blob/3837abf27fe5d9b090a7d530a81d6cebc634a79e/pkg/controller/controller_instance.go#L1752-L1755

Comment (nilebox) [reply pkg/controller/controller_instance.go]: Which makes me wonder if we may just invoke `removeInstanceFromRetryMap` inside `clearServiceInstanceCurrentOperation` method and remove this invocation from all other places?

Comment (jboyd01) [reply pkg/controller/controller_instance.go]: >We should probably remove instance if !shouldMitigateOrphan. I guess we could just move this line inside processProvisionFailure under condition

There are cases where we do retries (and want backoff) without doing orphan mitigation in between (retrying a failed update, retrying a provisioning after a 400 or 403).  I'll do some additional review, but at this point I'm not convinced doing the `removeInstancefromRetryMap` within `clearServiceInstanceCurrentOperation` is the right place.

File: pkg/controller/controller_instance.go (hunk 24 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Agreed, thanks

File: pkg/controller/controller_instance.go (hunk 25 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: `clearServiceInstanceCurrentOperation` is invoked a lot, I believe I saw it invoked as part of the orphan mitigation - from debug output, I am not comfortable doing the `removeInstanceFromRetryMap` in `clearServiceInstanceCurrentOperation` as I think it would prematurely clear out the instance.   @nilebox if you feel strongly about this let me know and I'll spend more time verifying.

**Comment by jboyd01** [comment]
I found `processServiceInstanceOperationError()`  is invoked if orphan mitigation hits an error, yet we aren't doing any backoff for orphan mitigation retries...  At this point it seems best to not include orphan mitigation as part of this scope, so I wanted to bump up the backoff time only for update errors here otherwise we may incorrectly increase backoff.  Very noticeable in integration tests where update or provisioning has failures along with orphan mitigation deprovisioning.  Is there a better way to check for update failure vs deprovision failure?
```golang
 func (c *controller) processServiceInstanceOperationError(instance *v1beta1.ServiceInstance, readyCond *v1beta1.ServiceInstanceCondition) error {
       // If error is from an update, assume a retry will happen, set a not-before time so we                                                                                                                                               
       // don't pound the Broker in a constant update/fail/update repeat loop.                                                                                                                                                              
       if strings.Contains(readyCond.Reason, "UpdateInstance") { 
               c.setNextOperationRetryTime(instance)
       }
```

File: pkg/controller/controller_instance.go (hunk 25 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: > I believe I saw it invoked as part of the orphan mitigation

@jboyd01 We only invoke `clearServiceInstanceAsyncOsbOperation` in case of orphan mitigation instead of `clearServiceInstanceCurrentOperation`. Orphan mitigation is considered part of the original Service Catalog operation.
Please check, I think it would make the code cleaner.

**Comment by nilebox** [comment]
@jboyd01  why don't you want to do backoff for orphan mitigation retries, sorry? Orphan mitigation is part of the original operation. If you don't do backoff for orphan mitigation, you won't do backoff for the operation when you retry provisioning after successful orphan mitigation? Isn't this the whole point of this PR to keep exponential backoff while `provision -> provision fail -> orphan mitigation -> provision -> ...`?

**Comment by jboyd01** [comment]
@nilebox The original issue is that provisioning a certain service keeps failing with a specific error.  OM (orphan mitigation) worked fine and the successful OM was part of the reason we didn't backoff on the next provision.  Given the way the original reconciliation & worker retry loops work, OM success was resetting the worker so there was no backoff on the retry to provision.  The solution I **had been** aiming for was `provision -> error-> OM -> backoff -> provision -> error -> OM -> backoff..... `

With your questioning, I see it would be pretty straight forward to use the same backoff value (if its set) prior to doing OM (deprovision).  Successful OM shouldn't reset the backoff though.  If OM fails, it would make sense to increase the backoff prior to retrying OM.  Once OM succeeds, the provision would fire immediately (it already spent the backoff prior to OM).   I think this means the provision failure loop would look like this as long as OM doesn't get an error:

`provision -> error-> backoff -> OM -> provision -> error -> backoff ->OM -> provision...`

and if there is an error doing OM I think we add another backoff:

`provision -> error-> backoff -> OM -> error -> backoff -> OM (success) -> provision -> error -> backoff ->OM -> provision...`

again noting that OM (success) does not reset the backoff.

A bonus to this is that in addition to provision and update, we'd add deprovision & OM to the backoff retry.

WDYT?

**Comment by nilebox** [comment]
Not sure if I fully understand. I don't like waiting _before_ performing OM.

Is your in-memory backoff flexible enough to set the backoff upon provision failure, but respect it only when we retry provisioning? That is what we really want in the end, I think.
i.e. in case of orphan mitigation:
```
provision -> error + update in-memory delay -> OM -> apply in-memory delay + provision -> ...
```
In other words, given that we consider OM to be part of the original operation, we don't want to apply your custom backoff there. Would it be possible?

Orphan mitigation could fail itself and should be retried with backoff delay as well... But in that case the normal rate limiting queue should take effect I think?

**Comment by nilebox** [comment]
To word it differently: we should only apply this custom backoff when we retry the operation.
Let me just give two examples:
- For **sync provisioning** the operation we retry is: "provision -> error -> OM". Then we try provisioning again, and that's where delay should be applied.
- For **async updates** the operation is "start updating -> poll last_operation -> failed". Then we try updating again, and that's where delay should be applied.

So we should be very clear about:
- When do we set the delay? When a retriable error has occured (so we 100% now we'll retry)
- When do we apply the delay? In the beginning of retrying the operation (see above)
- When do we reset the delay? When the operation succeeded, or finished with a terminal error.

File: pkg/controller/controller_instance.go [hunk 26]
```diff
@@ -1659,6 +1803,12 @@ func (c *controller) handleServiceInstanceReconciliationError(instance *v1beta1.
 // processServiceInstanceOperationError handles the logging and updating of
 // a ServiceInstance that hit a retryable error during reconciliation.
 func (c *controller) processServiceInstanceOperationError(instance *v1beta1.ServiceInstance, readyCond *v1beta1.ServiceInstanceCondition) error {
+	// If error is from an update, assume a retry will happen, set a not-before time so we
+	// don't pound the Broker in a constant update/fail/update repeat loop.
+	if strings.Contains(readyCond.Reason, "UpdateInstance") {
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: so instead of setting retry time under condition, we might just set the flag "delay required" there (unconditionally), and set the delay in the `reconcileServiceInstanceUpdate` if the flag is set.

File: pkg/controller/controller_instance.go (hunk 25 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: @jboyd01 You're right, we do invoke `clearServiceInstanceCurrentOperation` from the `processDeprovisionSuccess` method even it was orphan mitigation. We also invoke it in the beginning of orphan mitigation from `recordStartOfServiceInstanceOperation` method. So it's safer to invoke `removeInstancefromRetryMap` explicitly like you do, agreed.

File: pkg/controller/controller_instance.go [hunk 27]
```diff
@@ -339,6 +455,18 @@ func (c *controller) reconcileServiceInstanceAdd(instance *v1beta1.ServiceInstan
 		return nil
 	}
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: My proposed additional change: add `backoffRequired map[string]struct{}{}` to `retryQueue` struct, and check it at this line. If the flag is set, invoke `setNextOperationRetryTime` there instead of all other places.
All current usages of `setNextOperationRetryTime` replace with `setBackoffRequired(true)`.
Same change for `reconcileServiceInstanceUpdate` method.

**Comment by jboyd01** [comment]
@nilebox I've got the basics here from our discussion and your comments, but I want to refine, verify and update doc as we've discussed.  I still need to review this issue https://github.com/kubernetes-incubator/service-catalog/pull/2065#discussion_r193717455 as `processServiceInstanceOperationError()` is invoked for many reasons and I think I only want to trigger the pendingDelay if its for a failed update - I think we could bump the backoff too frequently otherwise.  I'm concerned about breaking this into a new function specific to update and invoking it at the right places (there are 7 direct invocations of this method, and an additional 13 invocations via `handleServiceInstanceReconciliationError()`)

**Comment by nilebox** [comment]
@jboyd01 maybe you should set and check for delay inside `recordStartOfServiceInstanceOperation`? I think it's invoked in the beginning of each retry, but worth checking.

**Comment by nilebox** [comment]
Alternatively, you could add condition for `if instance.Status.CurrentOperation == "" { ... }`.
I'm pretty sure that we reset `CurrentOperation` after successful OM, but not sure about update retry...

**Comment by jboyd01** [comment]
Nice @nilebox  - this looks like a much better approach.  Very specific and easy to rip out when we do the real rework in #2076.  I'll give this a go.

**Comment by jboyd01** [comment]
@nilebox I've mostly adapted what you suggested in https://github.com/kubernetes-incubator/service-catalog/pull/2065#issuecomment-395687966 with the exception that I do # 2 a bit earlier before the setting the status for the start of operation and logging that we're executing the broker action.  Also I left some cleanup in the success and terminal cases provisioning and update as it is clear (unlike deprovisioning) and I'd like to ensure we keep those in memory maps as minimally populated as possible.

**Comment by jboyd01** [comment]
@nilebox Could you give this a hopefully last review?  I believe its ready to go.

**Comment by carolynvs** [comment]
Due to a bug in our travis file, this PR must be rebased in order to get the Travis CI build to run for this PR.

**Comment by nilebox** [comment]
@jboyd01 builds seem to fail because of some trivial compilation error?
```
pkg/controller/controller_instance.go:459:34: not enough arguments in call to pretty.NewContextBuilder
	have (pretty.Kind, string, string)
	want (pretty.Kind, string, string, string)
make: *** [bin/service-catalog] Error 2
```

File: pkg/controller/controller_instance.go [hunk 28]
```diff
@@ -329,6 +367,165 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	glog.V(4).Infof("added %v to backoffBeforeRetrying", key)
+}
+
+// deleteInstanceKeysFromMapForAllGens purges out any instance entries ignoring the generation
+// Assumes the caller did the neccessary mutex locking for thread safety
+func deleteInstanceKeysFromMapForAllGens(m map[string]time.Time, key string) {
+	end := strings.Index(key, "@")
+	if end > 1 {
+		anyGeneration := key[0:end]
+		for k := range m {
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: Do we ever need to keep around the times from previous generations? Why don't we move the generation into the value part of the map entry instead of embedding it in the key part. That way you don't have to iterate over the entire map to clear out entries for old generations. When accessing the map, you would look up by namespace/name and then verify that the generation in the value part of the entry matches the current generation of the instance.

File: pkg/controller/controller_instance.go [hunk 29]
```diff
@@ -329,6 +367,165 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+		c.instanceOperationRetryQueue.mutex.RUnlock()
+	}
+
+	if delay > 0 {
+		msg := fmt.Sprintf("Delaying %s retry, next attempt will be after %s", operation, time.Now().Add(delay))
+		pcb := pretty.NewContextBuilder(pretty.ServiceInstance, instance.Namespace, instance.Name)
+		glog.V(2).Info(pcb.Message(msg))
+		c.recorder.Event(instance, corev1.EventTypeWarning, "RetryBackoff", msg)
+
+		// add back to workr queue to retry at the specified time
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: s/workr/worker/

File: pkg/controller/controller_instance.go [hunk 30]
```diff
@@ -329,6 +367,165 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	delay := time.Millisecond * 0
+
+	// if there is a pending delay, calculate it and clear it
+	c.instanceOperationRetryQueue.mutex.RLock()
+	_, exists := c.instanceOperationRetryQueue.backoffBeforeRetrying[key]
+	c.instanceOperationRetryQueue.mutex.RUnlock()
+
+	if exists {
+		c.instanceOperationRetryQueue.mutex.Lock()
+		if _, exists := c.instanceOperationRetryQueue.backoffBeforeRetrying[key]; exists {
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: Can you add a comment here that explains why the check in the `retryTime` queue is not needed in the case where the key has been purged from the `backoffBeforeRetrying` queue since the earlier check in this function?

File: pkg/controller/controller_instance.go [hunk 31]
```diff
@@ -89,20 +93,54 @@ const (
...
+	mutex sync.RWMutex // lock to be used for accessing all retryQueue fields
+
+	// All keys in retryTime, backoffBeforeRetrying, and rateLimiter are in the form of
+	// namespace/instance@generation
+
+	retryTime map[string]time.Time // If instance is in map, this is the earliest
+	// time at which an operation re-attempt should be made to ensure we don't
+	// overwhelm the broker with repeated requests.
+
+	backoffBeforeRetrying map[string]time.Time // An instance is added immediately
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: It would make things a lot cleaner if `retryTime` and `backoffBeforeRetrying` were combined into a single map whose value was a complex type. Then there is not extra wrangler to coordinate between the two and purge both maps.

File: pkg/controller/controller_instance.go (hunk 28 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: We dont keep or care about previous generations, I like the suggestion.

File: pkg/controller/controller_instance.go [hunk 32]
```diff
@@ -99,20 +101,47 @@ const (
...
 	clusterIdentifierKey string = "clusterid"
+
+	minBrokerOperationRetryDelay time.Duration = time.Second * 1
+	maxBrokerOperationRetryDelay time.Duration = time.Minute * 20
 )
 
+type backoffEntry struct {
+	generation          int64
+	calculatedRetryTime time.Time // earliest time we should retry
+	dirty               bool      // true indicates new backoff should be calculated
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: I find it cleaner to calculate the delay from start of request to start of request rather than from end of request to start of request. Asymptotically, it approaches the same delay in either case. I'm not convinced that it makes much difference operationally how the delay is calculated, so long as it is increasing. If the delay were calculated from start-to-start, then you would not need to keep track of a dirty bit. The `calculatedRetryTime` would be set directly in `setRetryBackoffRequired`.

File: pkg/controller/controller_instance.go [hunk 33]
```diff
@@ -341,6 +370,126 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	defer c.instanceOperationRetryQueue.mutex.Unlock()
+
+	// Ensure we only purge items that aren't being acted on by retries.
+	// Due to queues and potential delays, only remove entries that are at
+	// least maxBrokerOperationRetryDelay past next retry time to ensure
+	// entries are not prematurely removed
+	overDue := now.Add(-maxBrokerOperationRetryDelay)
+	purgedEntries := 0
+	for k := range c.instanceOperationRetryQueue.instances {
+		if due := c.instanceOperationRetryQueue.instances[k]; due.calculatedRetryTime.Before(overDue) {
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Yes, thanks!

File: pkg/controller/controller_instance.go [hunk 34]
```diff
@@ -341,6 +370,126 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+			glog.V(5).Infof("removing %s from instanceOperationRetryQueue which had retry time of %v", k, due)
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: absolutely, good catch

File: pkg/controller/controller_instance.go [hunk 35]
```diff
@@ -341,6 +370,126 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+			delete(c.instanceOperationRetryQueue.instances, k)
+			c.instanceOperationRetryQueue.rateLimiter.Forget(k)
+			purgedEntries++
+		}
+	}
+	glog.V(5).Infof("purged %v expired entries, instanceOperationRetryQueue queue length is %v", purgedEntries, len(c.instanceOperationRetryQueue.instances))
```
[the remark this answers is not in the document]
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: you are objecting to the text of the message right, not the calculation of the number of entries, right?

File: pkg/controller/controller_instance.go (hunk 32 above)
Comment (jboyd01) [reply pkg/controller/controller_instance.go]: One issue I fought with here is that in one of the non-happy path loops, you provision, fail, then have to go through orphan mitigation which may fail multiple times, then you do the retry.  On short backoffs the prior calculated retry added no delay because orphan mitigation took "so long".  

I agree its a bit convoluted, but this will be a short term solution (measured in months) before its replaced with a re-design for proper backoff/retry.

File: pkg/controller/controller_instance.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (staebler) [reply pkg/controller/controller_instance.go]: Yes, just the text of the message.

File: pkg/controller/controller_instance.go (hunk 32 above)
Comment (staebler) [reply pkg/controller/controller_instance.go]: OK. That makes sense.

**Comment by jboyd01** [comment]
The build failure in pull-service-catalog-xbuild is a pipeline problem - this builds fine and ready for final review, just need one more LGTM please.

File: pkg/controller/controller_instance.go [hunk 36]
```diff
@@ -341,6 +370,126 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+// been bumped since the instance was added to the retry map there will be no
+// backoff delay.
+func (c *controller) backoffAndRequeueIfRetrying(instance *v1beta1.ServiceInstance, operation string) bool {
+	pcb := pretty.NewInstanceContextBuilder(instance)
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf(pcb.Messagef("Couldn't create a key for object %+v: %v", instance, err))
+		return false
+	}
+	delay := time.Millisecond * 0
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: You don't need to declare a zero `delay` var there, you could just do 
```go
delay := retryEntry.calculatedRetryTime.Sub(now) 
```
below (replace `=` with `:=`)

Comment (jboyd01) [reply pkg/controller/controller_instance.go]: agreed @nilebox, I think this was left over after a refactor and I missed it.  This was just merged, next time I'm in here I'll clean it up.

File: pkg/controller/controller_instance.go [hunk 37]
```diff
@@ -341,6 +370,126 @@ func (c *controller) initOrphanMitigationCondition(instance *v1beta1.ServiceInst
...
+	key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(instance)
+	if err != nil {
+		glog.Errorf(pcb.Messagef("Couldn't create a key for object %+v: %v", instance, err))
+		return
+	}
+
+	c.instanceOperationRetryQueue.mutex.Lock()
+	defer c.instanceOperationRetryQueue.mutex.Unlock()
+	retryEntry, found := c.instanceOperationRetryQueue.instances[key]
+	if !found || retryEntry.generation != instance.Generation {
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: @jboyd01 I think we may need to also store and compare instance's `UID`.
@joshk has reported that when he deletes an old instance and creates a new one under the same name, he gets a `RetryBackoff` event immediately. I suspect this could happen when the old instance had a `Generation = 1` (created and never change) - and the new instance will get the same.

Comment (jboyd01) [reply pkg/controller/controller_instance.go]: Interesting.   Thanks for digging in on it @nilebox.

**Comment by nilebox** [comment]
@jboyd01 can we simply use `UID` as a key instead of `namespace/name` for this rate limiting map?

**Comment by jboyd01** [comment]
@nilebox Right, I was thinking the same thing.  Also looking into purging the entry from the retry maps after successfully doing non-orphan mitigation deprovision.
