### PR TITLE
Make it so that binding.spec.secretName defaults to binding name

### LINKED ISSUE #849: UPS sample has secret in the wrong place
Right now the UPS example, if I'm following it correctly, has people create broker and instance resources that are basically static. The unique part of things are in the binding because that's where we point to the secret that has the creds. This isn't correct. The secret/creds should be part of the instance so that as multiple apps bind to that instance those creds are injected by copying the secret from the instance data. They shouldn't have to specify the secret on each binding.

In the CF world, the equivalent would be something like:
```
cf create-user-provided-service my-db-mine -p "username, password"
```
where this is creating a new service instance called `my-db-mine`.  People can then bind to this instance w/o having to provide the creds each time.

I see code like this: https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/pkg/broker/user_provided/controller/controller.go#L83   which either seems to imply that UPS instances can have the creds as part of it or this is just a sample and not meant to be used to actually deploy UPS.

Perhaps the walkthru sample yaml just needs to be updated to add the creds to the instance instead - I'm not sure, the way UPS is layed out (code-wise and in the dir structure) is very confusing to me.

### PR DESCRIPTION
**Pull request by duglin**
modified walkthru too so that the instance has some credentials otherwise
the instance isn't very useful.

Closes: #850 
Closes #849

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

File: pkg/registry/servicecatalog/binding/strategy.go [hunk 1]
```diff
@@ -90,6 +90,11 @@ func (bindingRESTStrategy) PrepareForCreate(ctx genericapirequest.Context, obj r
 	}
 	// Is there anything to pull out of the context `ctx`?
 
+	// If not specified, make the SecretName default to the binding name
```
Comment (pmorie) [inline pkg/registry/servicecatalog/binding/strategy.go]: This goes in `pkg/apis/servicecatalog/v1alpha1/defaults.go` instead of the strategy.

File: test/integration/controller_test.go [hunk 2]
```diff
@@ -182,6 +181,14 @@ func TestBasicFlows(t *testing.T) {
 		t.Fatalf("error waiting for binding to become ready: %v", err)
 	}
 
+	newBinding, err := client.Bindings(testNamespace).Get(testBindingName, metav1.GetOptions{})
```
Comment (pmorie) [inline test/integration/controller_test.go]: The clientset test for bindings is probably a better place to check for this.

File: pkg/registry/servicecatalog/binding/strategy.go (hunk 1 above)
Comment (duglin) [inline pkg/registry/servicecatalog/binding/strategy.go]: ah, I figured there had to be a better place - just couldn't find it.  moved.

File: test/integration/controller_test.go (hunk 2 above)
Comment (duglin) [inline test/integration/controller_test.go]: where is that?

Comment (pmorie) [inline test/integration/controller_test.go]: test/integration/clientset_test.go

**Comment by MHBauer** [comment]
This is the PR with serialization test errors from the fuzzer.

**Comment by arschles** [comment]
@duglin what is the status of this PR?

**Comment by duglin** [comment]
I'm waiting for help from paul on what's up with the fuzzer.  @pmorie ?

**Comment by pmorie** [comment]
I am not going to have bandwidth before tues next week earliest, suggest
asking in api machinery

File: test/integration/controller_test.go (hunk 2 above)
Comment (duglin) [inline test/integration/controller_test.go]: moved

**Comment by duglin** [comment]
ok ready for another round of reviews

File: pkg/apis/servicecatalog/v1alpha1/types.go [hunk 3]
```diff
@@ -364,7 +364,7 @@ type BindingSpec struct {
 
 	// SecretName is the name of the secret to create in the Binding's
 	// namespace that will hold the credentials associated with the Binding.
-	SecretName string `json:"secretName"`
+	SecretName string `json:"secretName,omitempty"`
```
Comment (pmorie) [inline pkg/apis/servicecatalog/v1alpha1/types.go]: This shouldn't be omitempty, because it's not optional - you just added a default for it.

Comment (duglin) [inline pkg/apis/servicecatalog/v1alpha1/types.go]: While its not optional in etcd (because we end up defaulting it), it is optional for a client to send it in on the createBinding() request.  So, my understanding of `omitempty` is that its a signal to the json serializer that it doesn't need to send "", it can just skip that property. Which makes sense to me - but perhaps `omitempty` here has influence on other parts of the system we need to take into account??

Comment (pmorie) [inline pkg/apis/servicecatalog/v1alpha1/types.go]: Sorry for the latency, I actually think you're right and I was wrong.  I'll try to clarify the API conventions doc, since it doens't address this.
