### PR TITLE
Service instance deletion shouldn't be blocked by bindings if the instance was never provisioned

### LINKED ISSUE #1588: A ServiceBinding for which a Bind request has not been sent should not block deletion of a ServiceInstance
1) Create a ServiceInstance that is never provisioned successfully.
2) Create a ServiceBinding that references the ServiceInstance.
3) Delete the ServiceInstance.

The Controller should be able to completely delete the ServiceInstance. The Controller never sends a Bind request for the ServiceBinding that references the ServiceInstance because the ServiceInstance is never ready. The presence of the ServiceBinding, then, should not block deleting the ServiceInstance.

The following test should pass.
```
func TestServiceInstanceDeleteWithBlockedBindings(t *testing.T) {
	ct := controllerTest{
		t:      t,
		broker: getTestBroker(),
		setup: func(ct *controllerTest) {
			ct.osbClient.ProvisionReaction = &fakeosb.ProvisionReaction{
				Error: fmt.Errorf("retryable error"),
			}
		},
	}
	ct.run(func(ct *controllerTest) {
		instance := getTestInstance()
		if _, err := ct.client.ServiceInstances(instance.Namespace).Create(instance); err != nil {
			t.Fatalf("could not create instance: %v", err)
		}
		binding := getTestBinding()
		if _, err := ct.client.ServiceBindings(binding.Namespace).Create(binding); err != nil {
			t.Fatalf("could not create binding: %v", err)
		}
		if err := util.WaitForInstanceCondition(ct.client, instance.Namespace, instance.Name,
			v1beta1.ServiceInstanceCondition{
				Type:   v1beta1.ServiceInstanceConditionReady,
				Status: v1beta1.ConditionFalse,
				Reason: "ErrorCallingProvision",
			}); err != nil {
			t.Fatalf("error waiting for instance condition: %v", err)
		}
		if err := util.WaitForBindingCondition(ct.client, binding.Namespace, binding.Name,
			v1beta1.ServiceBindingCondition{
				Type:   v1beta1.ServiceBindingConditionReady,
				Status: v1beta1.ConditionFalse,
				Reason: "ErrorInstanceNotReady",
			}); err != nil {
			t.Fatalf("error waiting for binding condition: %v", err)
		}
		if err := ct.client.ServiceInstances(instance.Namespace).Delete(instance.Name, &metav1.DeleteOptions{}); err != nil {
			t.Fatalf("error deleting instance: %v", err)
		}
		if err := util.WaitForInstanceToNotExist(ct.client, instance.Namespace, instance.Name); err != nil {
			t.Fatalf("error waiting for instance to not exist: %v", err)
		}
		if err := ct.client.ServiceBindings(binding.Namespace).Delete(binding.Name, &metav1.DeleteOptions{}); err != nil {
			t.Fatalf("error deleting binding: %v", err)
		}
		if err := util.WaitForBindingToNotExist(ct.client, binding.Namespace, binding.Name); err != nil {
			t.Fatalf("error waiting for binding to not exist: %v", err)
		}
	})
}
```

### PR DESCRIPTION
**Pull request by witlessbird**
Closes #1588

### CODE REVIEW

**Comment by n3wscott** [comment]
ReadyFalse is not enough checking to assume the binding can be ignored. You need to also look at UnbindStatus for the binding to be sure the broker does not need to be notified of the bindings removal.

**Comment by witlessbird** [comment]
@n3wscott: could you clarify please? This only deals with instance removal, I assumed that binding will be (eventually?) cleaned up by the binding controller once it detects that the service instance is gone...

**Comment by n3wscott** [comment]
@witlessbird I do not believe an instance can be deleted until the bindings are deleted.

**Comment by witlessbird** [comment]
@n3wscott: I took a long look at binding reconciliation (here: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_binding.go#L178). 

It looks to me that binding in `ServiceBindingConditionReady` with `ConditionFalse` or `ServiceBindingConditionFailed` with `ConditionTrue` doesn't actually exist: there may or may not attempts to reconcile errors, but no active binding. The only exception to this I can think of is when a binding existed, but an update to it failed -- I'll take a look at that.

Additionally, my understanding is that should the service instance associated with a binding disappear, orphan mitigation will detect this and remove the binding.

**Comment by kibbles-n-bytes** [comment]
@witlessbird: Thanks for the PR!

I think filtering on the Ready condition being False is not quite enough, as @n3wscott said. The Ready condition can be False at any point before a binding is successfully created, but what we'd really like to know is whether a request has been sent to the broker yet for the binding. If it hasn't, then no big deal; we can delete the instance, and the binding will be updated to say it has no associated instance during the next reconcile.

If the request has been sent, however, then we should not allow the associated instance to be deleted, as bindings depend on their associated instance for all broker interactions (see: [here](https://github.com/kubernetes-incubator/service-catalog/blob/c1c69cf27b6a6864366580aa7cde55e9777590e4/pkg/controller/controller_binding.go#L215) and [here](https://github.com/kubernetes-incubator/service-catalog/blob/c1c69cf27b6a6864366580aa7cde55e9777590e4/pkg/controller/controller_binding.go#L732)) and thus we'll be blocked from being able to clean up the binding on the broker side. Orphan mitigation here unfortunately won't help, because it relies on this broker communication as well.

Instead of checking the conditions here, we should check whether `binding.Status.UnbindStatus == v1beta1.ServiceBindingUnbindStatusRequired`, and block instance deletion only if it is.

File: pkg/controller/controller_instance.go [hunk 1]
```diff
@@ -1843,7 +1843,12 @@ func (c *controller) serviceInstanceHasExistingBindings(instance *v1beta1.Servic
 	}
 	for _, binding := range bindingList {
 		if instance.Name == binding.Spec.ServiceInstanceRef.Name {
-			return true, nil
+			for _, condition := range binding.Status.Conditions {
+				if condition.Type == v1beta1.ServiceBindingConditionReady && condition.Status != v1beta1.ConditionFalse {
+					return true, nil
```
Comment (arschles) [inline pkg/controller/controller_instance.go]: I don't remember - what will happen when the user tries to delete the binding later? If fails b/c can't find the instance, I'd rather see that fixed in the same PR

Comment (kibbles-n-bytes) [reply pkg/controller/controller_instance.go]: @arschles If the binding has its `UnbindStatus` as `StatusNotRequired` (aka. there was never a request sent to the broker), it will be successfully deleted without having to look for the instance.

**Comment by witlessbird** [comment]
* updated to use ```binding.Status.UnbindStatus == v1beta1.ServiceBindingUnbindStatusRequired``` to check whether a service has actual bindings.

**Comment by witlessbird** [comment]
@kibbles-n-bytes: out of curiosity -- what would happen if a service was deleted after https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_binding.go#L215 but before https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_binding.go#L689?

**Comment by kibbles-n-bytes** [comment]
@witlessbird Hmm... For already provisioned instances, it seems to me there'd be a race. There's no way for the instance reconciler to know if a binding request has truly been sent to the broker or not, as it might just be looking at an out-of-date binding resource in the cache.

This is a tricky situation. We should probably limit the scope of this PR to just instances with DeprovisionStatus `NotRequired` corresponding to instances either never provisioned. In this case, we know:
1) There's no race with setting the `DeletionTimestamp` of the instance vs setting `DeprovisionStatus` to `Required`, as if the API server accepts a deletion of the instance, then the resource version will update and cause [here](https://github.com/kubernetes-incubator/service-catalog/blob/789c4b27e41ca619563fa2edf60a622a286220c0/pkg/controller/controller_instance.go#L584) to fail, which will make the reconciliation retry and never communicate with the broker.
2) There's no race with deleting the instance vs sending a bind request to the broker, as the binding would never get past [here](https://github.com/kubernetes-incubator/service-catalog/blob/789c4b27e41ca619563fa2edf60a622a286220c0/pkg/controller/controller_binding.go#L315), since the instance never would have become Ready at any time.

We might also be able to include DeprovisionStatus `Succeeded`, corresponding to instances that have either been orphan mitigated or have been deprovisioned already, but I need to think a bit more about the consequences of this, especially if we want to start to retry provision failures.

**Comment by witlessbird** [comment]
* updated to verify ```UnbindStatus``` only when ```DeprovisionStatus``` is ```ServiceInstanceDeprovisionStatusNotRequired```

**Comment by witlessbird** [comment]
I'll check if the above change will work for DeprovisionStatus ```Succeeded``` too.

**Comment by witlessbird** [comment]
* removed unused import

**Comment by witlessbird** [comment]
@kibbles-n-bytes: On the second thought I'm not sure I understand your comment re: DeprovisionStatus ```Succeeded```. Wouldn't getting to this state require removal of available bindings?

**Comment by kibbles-n-bytes** [comment]
@witlessbird Thinking about it now, it's safe; I was just heading out the office and didn't want to commit to it until I walked myself through the logic a bit more. If we have a DeprovisionStatus `Succeeded`, that implies that the instance has been orphan mitigated and at no point got a condition `Ready`, so no bindings could have gone through. And at that point, if we wanted to allow provision retries in the future, we'd be in the same situation as a DeprovisionStatus of `NotRequired`, which is safe as per above.

With that, the implementation could actually be just moving the `hasExistingBindings` check after the graceful deletion quick-exit block that currently immediately follows it, and no changes would be needed inside `c.serviceInstanceHasExistingBindings`.

**Comment by witlessbird** [comment]
> With that, the implementation could actually be just moving the hasExistingBindings check after the graceful deletion quick-exit block that currently immediately follows it, and no changes would be needed inside c.serviceInstanceHasExistingBindings.

Done. Also added a comment why we aren't trying to filter out bindings for which binding requests have not been sent.

**Comment by kibbles-n-bytes** [comment]
@witlessbird Thanks! You'll need to rebase now that some refactor work has gone in, but it shouldn't be too bad. Also could we get a couple unit tests for the `NotRequired` and `Succeeded` cases respectively?

**Comment by witlessbird** [comment]
* rebased.

> Also could we get a couple unit tests for the NotRequired and Succeeded cases respectively?

It appears these are already covered in https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_instance_test.go#L1732 and  https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_instance_test.go#L1839 respectively?

**Comment by kibbles-n-bytes** [comment]
@witlessbird Those tests are for instances without any bindings. We should add unit tests confirming that even with bindings, the instances in those cases are deleted successfully. I'd recommend not just adding a binding to those existing tests, though, as I think the cases are unique enough to warrant separate tests.

**Comment by witlessbird** [comment]
* Added tests to verify instance deletion with bindings present.

@kibbles-n-bytes: There's now quite a bit of code duplication in these tests -- perhaps we should parametrize them?

**Comment by witlessbird** [comment]
* signed CLA

**Comment by witlessbird** [comment]
@kibbles-n-bytes: any chance you could take another look at this?

File: pkg/controller/controller_instance_test.go [hunk 2]
```diff
@@ -1771,6 +1771,52 @@ func TestReconcileServiceInstanceDeleteFailedProvisionWithoutRequest(t *testing.
 	assertNumEvents(t, events, 0)
 }
 
+// TestReconcileServiceInstanceDeleteFailedProvisionWithoutRequestWithActiveBinding tests
+// that an instance that failed to provision without making a provision request
+// will be finalized even if it has binding(s) and no deprovision request will be sent to the broker.
+func TestReconcileServiceInstanceDeleteFailedProvisionWithoutRequestWithActiveBinding(t *testing.T) {
```
Comment (kibbles-n-bytes) [inline pkg/controller/controller_instance_test.go]: "Active" binding seems to imply to me that the binding resource was created at the broker, which isn't the case here. "Inactive" seems to convey the correct intent; the k8s resource was created, but the binding it represents hasn't been created yet.

File: pkg/controller/controller_instance_test.go [hunk 3]
```diff
@@ -1771,6 +1771,52 @@ func TestReconcileServiceInstanceDeleteFailedProvisionWithoutRequest(t *testing.
...
+	fakeKubeClient, fakeCatalogClient, fakeClusterServiceBrokerClient, testController, sharedInformers := newTestController(t, noFakeActions())
+
+	sharedInformers.ClusterServiceBrokers().Informer().GetStore().Add(getTestClusterServiceBroker())
+	sharedInformers.ClusterServiceClasses().Informer().GetStore().Add(getTestClusterServiceClass())
+	sharedInformers.ClusterServicePlans().Informer().GetStore().Add(getTestClusterServicePlan())
+	sharedInformers.ServiceBindings().Informer().GetStore().Add(getTestServiceBinding())
```
Comment (kibbles-n-bytes) [inline pkg/controller/controller_instance_test.go]: `getTestServiceBinding()` is a bit out of place here, because the resource it's creating is supposed to represent a binding that was created at the broker, and thus it has its `UnbindStatus` set to `Required` (looks like we don't set the Ready condition on it, though, which is a bit bizzare). Maybe we should create a new `getTestServiceBindingInactive()` function that represents a fresh binding resource from the broker.

**Comment by witlessbird** [comment]
* rebased
* parametrized tests in ```controller_instance_test.go``` to reduce code duplication
* added a helper function to create a new, "inactive" service binding

**Comment by witlessbird** [comment]
* fixed formatting

**Comment by arschles** [comment]
@kibbles-n-bytes answered my question (thanks!) so I've dismissed the 'x' on my review

**Comment by jboyd01** [comment]
LGTM, thanks a lot @witlessbird
