### PR TITLE
Reset RemovedFromBrokerCatalog when broker re-adds a removed service class

### LINKED ISSUE #1757: Service Catalog does not refresh ServiceClasses after removing from catalog
**Description of problem:**

If the Service Catalog calls the /v2/catalog endpoint and a provisioned ServiceInstance's ServiceClass is removed from the Broker's catalog response, the Service Catalog will mark it as:

`removedFromBrokerCatalog: true`

When the Service Broker recovers and the service class returns, the next relist by the Service Catalog should recover the missing Service Class and update the flag to false:

`removedFromBrokerCatalog: false`

How reproducible:
I had to modify the Automation Broker to randomly fail so that it would remove some Service specs from the /v2/catalog response.

**Steps to Reproduce:**
1. Have a test broker return say 4 service class specs from the `/v2/catalog` endpoint
2. Verify that the Service Catalog has 4 `ClusterServiceClasses`
3. Provision 1 of the Service Classes
4. Have the test broker return 3 service class specs from the `/v2/catalog`, the one that is missing MUST BE the one provisioned in step 3.
5. Have the Service Catalog relist with the test broker
6. Verify that the Provisioned Service Class reference is marked with:

  ` removedFromBrokerCatalog: true`

7. Now, have the test broker return all 4 service class specs from the /v2/catalog again.
8. Have the Service Catalog relist with the test broker
9. Verify that the flag for the provisioned Service Class ref again

**Actual results:**

10. The `removedFromBrokerCatalog:` flag remains **true** forever

**Expected results:**

10. The `removedFromBrokerCatalog:` flag should flip back to **false** once the service class spec returns to the `/v2/catalog` payload.

### PR DESCRIPTION
**Pull request by jboyd01**
fixes #1757 

Reconciliation loop was not resetting the RemovedFromBrokerCatalog status when the broker re-adds a previously delisted Cluster Service Class.  Fixed and added unit test.

### CODE REVIEW

File: pkg/controller/controller_broker.go [hunk 1]
```diff
@@ -17,12 +17,13 @@ limitations under the License.
 package controller
 
 import (
-	stderrors "errors"
 	"fmt"
 	"time"
 
 	"github.com/golang/glog"
 
+	stderrors "errors"
```
Comment (nilebox) [inline pkg/controller/controller_broker.go]: I believe this was an accidental move of import?
Also, probably should remove a blank line above (after `glog`) to avoid this `gofmt`'s weird behavior in future.

File: pkg/controller/controller_broker.go [hunk 2]
```diff
@@ -540,11 +541,27 @@ func (c *controller) reconcileClusterServiceClassFromClusterServiceBrokerCatalog
...
-	if _, err := c.serviceCatalogClient.ClusterServiceClasses().Update(toUpdate); err != nil {
+	updatedServiceClass, err := c.serviceCatalogClient.ClusterServiceClasses().Update(toUpdate)
+	if err != nil {
 		glog.Error(pcb.Messagef("Error updating %s: %v", pretty.ClusterServiceClassName(serviceClass), err))
 		return err
 	}
 
+	if updatedServiceClass.Status.RemovedFromBrokerCatalog {
+		glog.V(4).Info(pcb.Messagef("Resetting RemovedFromBrokerCatalog status on %s", pretty.ClusterServiceClassName(serviceClass)))
+		updatedServiceClass.Status.RemovedFromBrokerCatalog = false
```
Comment (nilebox) [inline pkg/controller/controller_broker.go]: I wonder if we can check somehow that this is the same class and not a completely new one with a clashing name.

Comment (nilebox) [reply pkg/controller/controller_broker.go]: OSB spec is not clear about whether the name can be reused after the service was deleted from the catalog:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-object

| Response Field | Type | Description |
| --- | --- | --- |
| name* | string | A CLI-friendly name of the service. MUST only contain alphanumeric characters and hyphens (no spaces). MUST be unique across all service objects returned in this response. MUST be a non-empty string. |

It only says that the name must be unique within a response, which implicitly allows to redeclare a new service with a clashing name once the old one was removed.

Comment (nilebox) [reply pkg/controller/controller_broker.go]: Ah we use `ID` as a Kubernetes resource name there, which must be globally unique. All good 👍

**Comment by nilebox** [comment]
@jboyd01 can you fix the import ordering, and merge after?

File: pkg/controller/controller_broker.go (hunk 1 above)
Comment (jboyd01) [reply pkg/controller/controller_broker.go]: done, I saw and meant to fix on initial commit.  Thanks.
