### PR TITLE
Do not block instance spec changes unless there is an on-going operation

### LINKED ISSUE #1533: Changing plan name of ServiceInstance to non-existent plan blocks future modifications to the ServiceInstance
When the plan name of a ServiceInstance is set to a non-existent plan, the Controller indefinitely fails trying to reconcile the ServiceInstance, due to failing to resolve the plan. The API Server blocks changes to the ServiceInstance while there is a pending change (i.e., while the generation and reconciled generation differ). Consequently, the user is unable to ever make any further changes to the ServiceInstance other than deleting it.

### PR DESCRIPTION
**Pull request by staebler**
Fixes #1533.

Change the validator for ServiceInstance so that it only blocks spec changes when there is an on-going operation. If the plan was changed to a non-existent plan, then there will not be an on-going operation for the ServiceInstance since the reconciliation of the pending change will fail when resolving the plan, prior to the point where the Controller sends a request to the broker.

Let's consider the case where the Controller is doing reconciliation on a ServiceInstance at the same time that the API Server is effecting a change to the same ServiceInstancee. In that case, the API Server will accept the requested spec change because the request from the Controller to the API Server to update the status of the ServiceInstance with the current operation has not been processed by the API Server yet. When the API Server processes the status change from the Controller, the API Server will reject the status change because the ServiceInstance used by the Controller will be out-of-date at that point. Since the status update will fail, the Controller will fail the reconciliation of the ServiceInstance. Later, the Controller will try reconciliation again with the new version of the ServiceInstance, with the updated spec.

### CODE REVIEW

File: pkg/apis/servicecatalog/validation/instance.go [hunk 1]
```diff
@@ -262,7 +262,7 @@ func validateServiceInstanceUpdate(instance *sc.ServiceInstance) field.ErrorList
 // to the spec to go through.
 func internalValidateServiceInstanceUpdateAllowed(new *sc.ServiceInstance, old *sc.ServiceInstance) field.ErrorList {
 	errors := field.ErrorList{}
-	if old.Generation != new.Generation && old.Status.ReconciledGeneration != old.Generation {
+	if old.Generation != new.Generation && old.Status.ReconciledGeneration != old.Generation && old.Status.CurrentOperation != "" {
```
Comment (kibbles-n-bytes) [inline pkg/apis/servicecatalog/validation/instance.go]: We should be able to remove the section about `old.Status.ReconciledGeneration != old.Generation`. We should never have the case where the current operation is set but the reconciled generation matches the generation. (Though looks like this is another gap in our validation functions)

Comment (kibbles-n-bytes) [reply pkg/apis/servicecatalog/validation/instance.go]: Ah, not a gap; found the check [here](https://github.com/kubernetes-incubator/service-catalog/blob/f86b8aaa4c5cf64e58717289b49e8898546a18d8/pkg/apis/servicecatalog/validation/instance.go#L244). So yes, this should be able to be removed safely.

Comment (staebler) [reply pkg/apis/servicecatalog/validation/instance.go]: I think that I had in my head that there was an edge case where the current update could be changing the reconciled generation so that it matched the generation, which is why the check is for the old reconciled generation and old generation. But that doesn't make sense since we should only be updating *either* the spec *or* the status. I'll remove the unneeded part.
