### PR TITLE
Bug 1539102 - Use userInfo for Originating-Identity so extras is correct.

### LINKED ISSUE #1701: X-Broker-API-Originating-Identity Does not have extras
Service Catalog does not send over extra fields in `extra` instead it is a top level of the created object.

Actual results:
```
X-Broker-API-Originating-Identity Header: kubernetes eyJncm91cHMiOlsic3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgiLCJzeXN0ZW06YXV0aGVudGljYXRlZCJdLCJzY29wZXMuYXV0aG9yaXphdGlvbi5vcGVuc2hpZnQuaW8iOlsidXNlcjpmdWxsIiwidXNlcjpsaXN0LXByb2plY3RzIiwidXNlcjppbmZvIiwicm9sZTphZG1pbjpuZXctcHJvamVjdDohIl0sInVpZCI6IiIsInVzZXJuYW1lIjoiZGV2ZWxvcGVyIn0=

{"groups":["system:authenticated:oauth","system:authenticated"],"scopes.authorization.openshift.io":["user:full","user:list-projects","user:info","role:admin:new-project:!"],"uid":"","username":"developer"}
```
Expected results:
```
eyJncm91cHMiOlsic3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgiLCJzeXN0ZW06YXV0aGVudGljYXRlZCJdLGV4dHJhOnsic2NvcGVzLmF1dGhvcml6YXRpb24ub3BlbnNoaWZ0LmlvIjpbInVzZXI6aW5mbyJdfSwidWlkIjoiIiwidXNlcm5hbWUiOiJkZXZlbG9wZXIifQo=

{"groups":["system:authenticated:oauth","system:authenticated"],extra:{"scopes.authorization.openshift.io":["user:info"]},"uid":"","username":"developer"}
```

### PR DESCRIPTION
**Pull request by shawn-hurley**
fixes #1701

### CODE REVIEW

File: pkg/controller/originating_identity.go [hunk 1]
```diff
@@ -25,23 +25,13 @@ import (
...
 	}
-	oiFields := map[string]interface{}{}
-	oiFields[originatingIdentityUsername] = userInfo.Username
-	oiFields[originatingIdentityUID] = userInfo.UID
-	oiFields[originatingIdentityGroups] = userInfo.Groups
-	for k, v := range userInfo.Extra {
-		oiFields[k] = v
-	}
-	oiValue, err := json.Marshal(oiFields)
+	oiValue, err := json.Marshal(userInfo)
```
Comment (MHBauer) [inline pkg/controller/originating_identity.go]: The userinfo does have the exact fields that were needed. I wonder why we did this in the past?
