### PR TITLE
Fix event recorder scheme

### LINKED ISSUE #1628: Endpoints kind not registered in the schema
Found this in controller-manager logs:
```
E1215 09:25:55.121886       1 event.go:260] Could not construct reference to:
'&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"service-catalog-controller-manager", GenerateName:"", Namespace:"service-catalog", SelfLink:"/api/v1/namespaces/service-catalog/endpoints/service-catalog-controller-manager", UID:"e31348c3-d303-11e7-8316-06ee2612ca84", ResourceVersion:"13123257", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63647336730, loc:(*time.Location)(0x25ae700)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"service-catalog-controller-manager-7d4bd8bd6-l5wj7-external-service-catalog-controller\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-12-15T09:25:55Z\",\"renewTime\":\"2017-12-15T09:25:55Z\",\"leaderTransitions\":6}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}'
due to: 'no kind is registered for the type v1.Endpoints'. Will not report event: 'Normal' 'LeaderElection' 'service-catalog-controller-manager-7d4bd8bd6-l5wj7-external-service-catalog-controller became leader'
I1215 09:25:55.122011       1 leaderelection.go:184] successfully acquired leaseservice-catalog/service-catalog-controller-manager
```
Service Catalog 0.1.3

### PR DESCRIPTION
**Pull request by ash2k**
Fixes #1628.

### CODE REVIEW

File: cmd/controller-manager/app/controller_manager.go [hunk 1]
```diff
@@ -187,10 +190,25 @@ func Run(controllerManagerOptions *options.ControllerManagerServer) error {
...
+
 	eventBroadcaster := record.NewBroadcaster()
-	eventBroadcaster.StartLogging(glog.Infof)
-	eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: k8sKubeClient.CoreV1().Events("")})
-	recorder := eventBroadcaster.NewRecorder(api.Scheme, v1.EventSource{Component: controllerManagerAgentName})
+	loggingWatch := eventBroadcaster.StartLogging(glog.Infof)
+	defer loggingWatch.Stop()
+	recordingWatch := eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: k8sKubeClient.CoreV1().Events("")})
+	defer recordingWatch.Stop()
+	recorder := eventBroadcaster.NewRecorder(eventsScheme, v1.EventSource{Component: controllerManagerAgentName})
```
Comment (MHBauer) [inline cmd/controller-manager/app/controller_manager.go]: is there any "wait to be ready" type function that needs to be called? I'm thinking of how informers work. I think because this is a push, where that is a watch, we're fine without any such call being necessary.

File: cmd/controller-manager/app/controller_manager.go [hunk 2]
```diff
@@ -187,10 +190,25 @@ func Run(controllerManagerOptions *options.ControllerManagerServer) error {
 
 	// Create event broadcaster
 	glog.V(4).Info("Creating event broadcaster")
+	eventsScheme := runtime.NewScheme()
+	// We use ConfigMapLock/EndpointsLock which emit events for ConfigMap/Endpoints and hence we need core/v1 types for it
```
Comment (MHBauer) [inline cmd/controller-manager/app/controller_manager.go]: good comments.

File: cmd/controller-manager/app/controller_manager.go (hunk 1 above)
Comment (ash2k) [reply cmd/controller-manager/app/controller_manager.go]: No, afaik. Events work for instances and bindings, for example.

**Comment by jboyd01** [comment]
I had spent some time investigating this issue yesterday and found the Scheme we were using was "bad" - I  found that using Scheme from k8s.io/client-go/kubernetes/scheme also addressed the eventing issue, though I'm not certain it had Catalog's types registered.  Your fix LGTM.

**Comment by carolynvs** [comment]
I was wondering about a test myself but wasn't sure how to even go about testing it? I'll hold off on merging for a sec just in case.

File: cmd/controller-manager/app/controller_manager.go (hunk 1 above)
Comment (MHBauer) [reply cmd/controller-manager/app/controller_manager.go]: That's my understanding, yes.

**Comment by jboyd01** [comment]
When I was working on a fix separately yesterday, I changed https://github.com/kubernetes-incubator/service-catalog/blob/master/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go#L199 to add `le.config.Lock.RecordEvent("testing event recording, still leading")`  and verified this shows up when you do a `kubectl describe configmap service-catalog-controller-manager -n catalog`

Probably achievable with an integration test, but I'm not certain its worth the effort.

**Comment by carolynvs** [comment]
Executive Decision: :shipit:
