### PR TITLE
Load all client auth plugins in the cli

### LINKED ISSUE #1676: svcat fails when used with Google Cloud cluster: No Auth Provider for name "gcp"
Looks like the auth plugins for the Go K8S client aren't initialized, so it doesn't know how to communicate with a GKE cluster. For the e2e binary, I remember having to add `import _ "k8s.io/client-go/plugin/pkg/client/auth"`, and that fixed things. However, it looks like Service Catalog doesn't "import _" anything similar; does anyone know how it successfully sets up the auth?

### PR DESCRIPTION
**Pull request by carolynvs**
The go-client auth plugins rely on registration that occurs during init. The auth package handles importing all the client packages for side effects, so we can just import the auth package and that will take care of every plugin.

@kibbles-n-bytes I don't have a gcp cluster to test against, would you be willing to try this out? 

Closes #1676.

### CODE REVIEW

**Comment by kibbles-n-bytes** [comment]
It works! Thanks for the patch @carolynvs :smile:

File: pkg/svcat/kube/kube.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package kube
 
 import (
+	_ "k8s.io/client-go/plugin/pkg/client/auth" // Load all client auth plugins for gcp, azure, etc
```
Comment (MHBauer) [inline pkg/svcat/kube/kube.go]: I still hate inits, is there a function we can explicitly call to opt-in instead?

Comment (carolynvs) [reply pkg/svcat/kube/kube.go]: There isn't. The init functions for the plugins all rely on unexported functions.

**Comment by duglin** [comment]
LGTM
