### PR TITLE
Display parameters in svcat describe instance/binding output

### LINKED ISSUE #1808: svcat describe instance/binding should include the parameters
When troubleshooting why a provision called failed, it helps to see the parameters passed to the broker, both for the instance and the binding:

```console
$ svcat describe instance NAME
  Name:        wordpress-wordpress-mysql-instance
  Namespace:   svcatt
  Status:      Failed - Provision call failed: (no description provided) @ 2018-03-06 19:40:27 +0000 UTC
  Class:       azure-mysql
  Plan:        basic50

Parameters:
  Firewall End IP Address:    255.255.255.255
  Firewall Start IP Address:  0.0.0.0
  Location:                   centralus
  Resource Group:             default
  Ssl Enforcement:            disabled

...

$ svcat describe binding wordpress-wordpress-mysql-binding
  Name:        wordpress-wordpress-mysql-binding
  Namespace:   svcatt
  Status:      NotReady
  Instance:    wordpress-wordpress-mysql-binding

Parameters:
  No parameters defined
```

### PR DESCRIPTION
**Pull request by carolynvs**
When an instance or a binding has parameters set, display in yaml format. Omit the entire section otherwise.

```console
$ svcat describe instance knotted-otter-wordpress-mysql-instance
  Name:        knotted-otter-wordpress-mysql-instance
  Namespace:   default
  Status:      Ready - The instance was provisioned successfully @ 2018-03-21 19:41:13 +0000 UTC
  Class:       azure-mysql
  Plan:        standard100

Parameters:
  firewallRules:
  - endIPAddress: 255.255.255.255
    name: AllowAll
    startIPAddress: 0.0.0.0
  location: eastus
  resourceGroup: default
  sslEnforcement: disabled

Bindings:
                  NAME                    STATUS
+---------------------------------------+--------+
  carolyn                                 Ready
  knotted-otter-wordpress-mysql-binding   Ready

$ ./bin/svcat/svcat describe binding carolyn
  Name:        carolyn
  Namespace:   default
  Status:      Ready - Injected bind result @ 2018-03-21 19:56:07 +0000 UTC
  Instance:    knotted-otter-wordpress-mysql-instance

Parameters:
  foo: bar

$ ./bin/svcat/svcat describe binding knotted-otter-wordpress-mysql-binding
  Name:        knotted-otter-wordpress-mysql-binding
  Namespace:   default
  Status:      Ready - Injected bind result @ 2018-03-21 19:41:20 +0000 UTC
  Instance:    knotted-otter-wordpress-mysql-instance
```
Closes #1808

### CODE REVIEW

File: cmd/svcat/output/binding.go [hunk 1]
```diff
@@ -65,15 +65,20 @@ func WriteBindingList(w io.Writer, bindings ...v1beta1.ServiceBinding) {
...
 		{"Name:", binding.Name},
 		{"Namespace:", binding.Namespace},
 		{"Status:", getBindingStatusFull(binding.Status)},
 		{"Instance:", binding.Spec.ServiceInstanceRef.Name},
 	})
-
 	t.Render()
+
+	// If available, show the parameters as they were sent to the broker, otherwise show what was requested
+	if binding.Status.ExternalProperties != nil && binding.Status.ExternalProperties.Parameters != nil {
```
Comment (n3wscott) [inline cmd/svcat/output/binding.go]: Is it the case that you never want to see the Spec.Parameters if you have Status.ExternalProperties.Parameters?

it is one or the other?

Comment (carolynvs) [reply cmd/svcat/output/binding.go]: I wasn't sure what was a good design choice for all users, so I went with what I personally prefer. Don't show me the params twice, and I favor knowing what was actually sent to the broker, vs what is in the spec.

Suggestions welcome on how to either make that more clear, or if you have a different UX in mind! ✨

Comment (n3wscott) [reply cmd/svcat/output/binding.go]: @kibbles-n-bytes do you have an opinion?

Comment (kibbles-n-bytes) [reply cmd/svcat/output/binding.go]: Hmm... I'm inclined to say you'd want to actually see both. :frowning_face: I think describing the resource should still be showing its real state, even if its broken.

Comment (carolynvs) [reply cmd/svcat/output/binding.go]: @n3wscott I like your suggestion the best! 

Since the data is always available, I vote we just diff and point out differences when they exist proactively, and otherwise have the user show these other fields explicitly with a flag when desired. What about this?

Happy Path (current PR)
```console
$ svcat describe instance puppy-kisses
Name: puppy-kisses
... TRUNCATED

Parameters:
  type: golden-retriever
  age: 3
```

Looking at all the things because I want to
```console
$ svcat describe instance puppy-kisses --external-properties
Name: puppy-kisses
... TRUNCATED

Parameters:
  type: golden-retriever
  age: 3

External Properties:
  Cluster Service Plan External Name: Goldy
  Cluster Service Plan External ID: abc123
  
  Parameters:
    type: golden-retriever
    age: 3

  Parameter Checksum: abc1232
```

svcat detects when things are different and automatically shows me a diff
```console
$ svcat describe instance puppy-kisses
Name: puppy-kisses
... TRUNCATED

Parameters:
  type: golden-retriever
  age: 3

The following differences between the spec and the status have been identified:
  Paramters:
    age-spec:   3
    age-status: 
```

Comment (kibbles-n-bytes) [reply cmd/svcat/output/binding.go]: Yeah, I think that would work best! I think I have a slight preference over formatting the "diff" section more as the following:

```
The following differences between the spec and the status have been identified:
  Spec:
    Parameters:
      type: corgi
      age: 5
    
  Status:
    Parameters:
      type: golden-retriever
      age: 3
```

Unless there's a better way to diff right next to each other in the yaml without having to rename the key, since there's a potential for the key to clash or be unclear since JSON allows any Unicode character.

Comment (carolynvs) [reply cmd/svcat/output/binding.go]: I just made up a diff format for my example. 😀  I am pretty sure there are existing diff libraries out there that we could reuse, or if we don't like any of the diff formats, I like your idea over writing our own diff-magic. 👍

**Comment by carolynvs** [comment]
I've updated this PR to only show `Spec.Parameters` and will follow up with one for `--external-properties` and auto-diffing.
