### PR TITLE
Controller-manager crash loops if API server is not available on startup

### LINKED ISSUE #1376: Controller-manager will crash loop if API server is not immediately available on startup
The controller-manager will crash (without retrying) if the the API server is not available when it starts.  This means, for example, that the controller-manager pod routinely crashloops after the helm chart is installed.
A number of people have reported this to me; users find it confusing and it can be a red herring.

We should retry with backoff when this happens.

### PR DESCRIPTION
**Pull request by jboyd01**
fixes #1376 

When Controller and API Server are started at the same time with API Aggregation enabled, it may take some time before Catalog registration shows up in API Server.  Re-query API Server several times if necessary to get the catalog resources.

I've always seen this issue when running with Kubernetes hack/local-up-cluster so it was an easy issue to reproduce and address.

### CODE REVIEW

File: cmd/controller-manager/app/controller_manager.go [hunk 1]
```diff
@@ -293,21 +293,37 @@ func StartControllers(s *options.ControllerManagerServer,
...
-	coreClient, err := kubernetes.NewForConfig(coreKubeconfig)
-	if err != nil {
-		glog.Fatal(err)
+	// When Catalog Controller and Catalog API Server are started at the
+	// same time with API Aggregation enabled, it may take some time before
+	// Catalog registration shows up in API Server.  Re-query several times if
+	// necessary.
+	var availableResources map[schema.GroupVersionResource]bool
+	catalogResourceAvailable := false
+	const maxAttempts = 4
```
Comment (staebler) [inline cmd/controller-manager/app/controller_manager.go]: Is there a reason to bail out of the controller-manager at all instead of sitting in this loop with an exponential backoff indefinitely? Is there something that we gain from register a crash in the pod's status after 40 seconds that is better than registering it immediately as is done currently in master?

File: cmd/controller-manager/app/controller_manager.go [hunk 2]
```diff
@@ -293,21 +293,37 @@ func StartControllers(s *options.ControllerManagerServer,
...
+		if err != nil {
+			return err
+		}
+		catalogResourceAvailable = availableResources[catalogGVR]
+		if !catalogResourceAvailable {
+			if attempt+1 <= maxAttempts {
+				glog.V(5).Info("Catalog resources are not available from API Server, will reattempt")
+				time.Sleep(10 * time.Second)
+			} else {
+				glog.V(5).Infof("Failed to get catalog resources from API Server after %d attempts.", attempt)
```
Comment (staebler) [inline cmd/controller-manager/app/controller_manager.go]: I don't like delaying returning from the function until later, when the context has been somewhat lost. Let's just do the return here.

I would also prefer to just break out of the for loop when the catalog resource is available rather than carrying around the `catalogResourceAvailable` variable.

**Comment by pmorie** [comment]
@jboyd01 so does this fix the crashloop that normally happens when you install the chart?

File: cmd/controller-manager/app/controller_manager.go (hunk 1 above)
Comment (jboyd01) [reply cmd/controller-manager/app/controller_manager.go]: I was hesitant to wait forever. there is nothing magic about 40 other then in my testing it may take upwards of 30 seconds to succeed when my machine is cpu challenged.

**Comment by jboyd01** [comment]
Yes @pmorie, this addresses the crashloop.

File: cmd/controller-manager/app/controller_manager.go (hunk 2 above)
Comment (jboyd01) [reply cmd/controller-manager/app/controller_manager.go]: refined per @staebler's review

File: cmd/controller-manager/app/controller_manager.go [hunk 3]
```diff
@@ -293,58 +293,70 @@ func StartControllers(s *options.ControllerManagerServer,
...
-	availableResources, err := getAvailableResources(serviceCatalogClientBuilder)
-	if err != nil {
-		return err
+	// When Catalog Controller and Catalog API Server are started at the
+	// same time with API Aggregation enabled, it may take some time before
+	// Catalog registration shows up in API Server.  Re-query several times if
+	// necessary.
+
+	const maxAttempts = 4
+	for attempt := 1; ; attempt++ {
```
Comment (pmorie) [inline cmd/controller-manager/app/controller_manager.go]: you should use `wait.ExponentialBackoff` here instead, see: https://github.com/kubernetes-incubator/service-catalog/blob/master/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go#L192

**Comment by jboyd01** [comment]
Using `wait.ExponentialBackoff` to retry the fetch of the catalog registration every 10 seconds for up to 3 minutes.  If not found within this time period fail with an error as we always have.  I feel its better to terminate with an error then to remain in the retry loop.  I didn't do exponential backoff, a retry every 10 seconds achieves a balance between not overwhelming the api server and still getting a quick startup.

File: cmd/controller-manager/app/controller_manager.go [hunk 4]
```diff
@@ -293,58 +293,76 @@ func StartControllers(s *options.ControllerManagerServer,
...
+	// When Catalog Controller and Catalog API Server are started at the
+	// same time with API Aggregation enabled, it may take some time before
+	// Catalog registration shows up in API Server.  Attempt to get resources
+	// every 10 seconds and quit after 3 minutes if unsuccessful.
+
+	backoff := wait.Backoff{
+		Duration: 10 * time.Second,
+		Factor:   1,
+		Jitter:   0,
+		Steps:    19,
```
Comment (jpeeler) [inline cmd/controller-manager/app/controller_manager.go]: Am I misunderstanding or is 19 iterations actually 3 min 10 sec? If so, 18 may be better if for no reason other than to match the above comment.

Comment (jboyd01) [reply cmd/controller-manager/app/controller_manager.go]: The first poll happens immediately, 18 more gives us a maximum  of 3 minutes polling.

**Comment by jboyd01** [comment]
@MHBauer I don't believe changing the readiness probe is going to make a difference.  In the error case, the Controller starts, reaches out to the aggregated API server, gets a response back, but determines that the catalog service hasn't been registered yet.  Without the retry logic, the controller fails startup and exits.  As you indicated, Kubernetes will do the right thing and keep restarting the controller, but in many environments you see that the Controller pod failed 2 or 3 times and will be in an Error or CrashLoopBackOff state for the first minute or so after helm install.  It may leave you wondering if there are other problems.

**Comment by MHBauer** [comment]
I think we should let it fail. With kube, the user is often left wondering if something is wrong until it works. I do not see any reason to code around this behavior for the sake of the prettiness of seeing a 0 in the restart column.

**Comment by staebler** [comment]
For reference, when kube-controller-manager starts, it polls kube-apiserver once per second for 10 seconds wiating for kube-apiserver to start. If kube-apiserver is not responsive after 10 seconds, kube-controller-manager exits with exit code 255. So there is precedence for the approach of polling for a short period of time and then exiting.

https://github.com/kubernetes/kubernetes/blob/4e2f5e2212b05a305435ef96f4b49dc0932e1264/cmd/kube-controller-manager/app/controllermanager.go#L375-L393

File: cmd/controller-manager/app/controller_manager.go [hunk 5]
```diff
@@ -293,58 +293,76 @@ func StartControllers(s *options.ControllerManagerServer,
...
+	}
+	var availableResources map[schema.GroupVersionResource]bool
+	err := wait.ExponentialBackoff(
```
Comment (staebler) [inline cmd/controller-manager/app/controller_manager.go]: `wait.PollImmediate` more closely matches what we are doing here. Since the factor of the exponential backoff is 1, it looks deceiving to use `wait.ExponentialBackoff`.

**Comment by jpeeler** [comment]
I was able to add the health check on the /healthz endpoint (that's missing in our version of getAvailableResources), increase the poll time, and have 0 restarts of the controller. It's definitely an easier fix.

**Comment by jboyd01** [comment]
@staebler I couldn't agree more with your comment about using PollImmediate() vs ExponentialBackoff(), I've updated accordingly.

Jeff and I discussed, I tried his alternate approach with ensuring the /healthz ping is successful in the condition function right after the call to clientBuilder.Client(controllerDiscoveryAgentName)...  I couldn't get this to prevent the failed controller startups, I still ended up with 2 failures each time I tested.

**Comment by staebler** [comment]
The approach taken in k8s controllers that our controller does not do is to have the controller wait for the lister to sync when starting. If we did that instead of waiting for the ClusterServiceBroker kind to be available, that put service catalog more in line with other controllers.

https://github.com/kubernetes/kubernetes/blob/ccb15fb498352cad3f582cce0ade4e99efe0f82f/pkg/controller/deployment/deployment_controller.go#L156

https://github.com/kubernetes/kubernetes/blob/ccb15fb498352cad3f582cce0ade4e99efe0f82f/pkg/controller/controller_utils.go#L1015-L1028

**Comment by pmorie** [comment]
Is this ready for review?  It's not clear to me from the comments.

**Comment by jboyd01** [comment]
@pmorie IMO its ready

**Comment by arschles** [comment]
I don't love this change because I'd rather let Kubernetes do its thing like @MHBauer said, but I do think it would help operationally over time. Here's what we've seen:

1. API server "flaps" due to etcd outages. As we know, one of these cases is almost guaranteed to happen over days in a cloud environment:
    - External etcd becomes unavailable due to of network blips, and recovery takes 30+ seconds
    - The ephemeral in-pod etcd flaps and takes down the whole API server
2. controller-manager goes down initially b/c watch stream is severed and/or API server pings fail
3. Kubernetes restarts the controller-manager, which immediately crashes again b/c api server is still not back to healthy
4. controller-manager quickly goes into CrashLoopBackoff
4. Once the API server is back up and stable, the controller-manager is already in CrashLoopBackoff and won't come back for minutes

The end result is that we are likely to have long (minutes) controller-manager outages when the API server has short-lived issues. This change would at least reduce the likelihood of long (minutes) outages of controller-manager

**Comment by jboyd01** [comment]
With more investigation, testing, discussion and review with @pmorie and @staebler we've come to the conclusion that the initial change proposed here with the new  three minute PollImediate loop waiting for the Catalog custom resources  to be registered with the aggregated API server is necessary, and additionally there should be a new check to ensure the caches have synchronized prior to starting the controller as detailed in https://github.com/kubernetes-incubator/service-catalog/pull/1591#issuecomment-346521482.   A follow on PR will add that cache check.

**Comment by MHBauer** [comment]
This seems like something that should be provided upstream by client-go, as it is the controller toolbox.
