### PR TITLE
Use Plan ID from ExternalProperties when deprovisioning instance

### LINKED ISSUE #1499: Deleting ServiceInstance after changing to invalid Plan crashes controller-manager
1. Create a ServiceInstance.
2. Change `ClusterServicePlanExternalName` to the name of a non-existent plan.
3. Delete the ServiceInstance.

When the ServiceInstance is updated, the API Server will clear the `ClusterServicePlanRef`. The Controller will fail reconciliation because of the missing plan and not make any changes to `ClusterServicePlanRef`.

When the ServiceInstance is deleted, the Controller will not make any attempt to resolve the class or plan references. But the Controller will attempt to get the class and plan for the instance. This will cause a panic error trying to get `Name` from the nil `ClusterServicePlanRef`.

### PR DESCRIPTION
**Pull request by staebler**
Fixes #1499.

* Store the External ID of the Plan in the `ExternalProperties` of ServiceInstance.
* When deprovisioning, use the Plan ID from `ExternalProperties` when available. If not, then fall back to using the Plan ID referenced from `ClusterServicePlanRef`. If that is not available either, then error out of reconciliation.

### CODE REVIEW

File: pkg/controller/controller_instance.go [hunk 1]
```diff
@@ -1968,7 +1994,7 @@ func (c *controller) checkForRemovedClassAndPlan(instance *v1beta1.ServiceInstan
 	// Regardless of what's been deleted, you can always update
 	// parameters (ie, not change plans)
 	if !isProvisioning && instance.Status.ExternalProperties != nil &&
-		servicePlan.Spec.ExternalName == instance.Status.ExternalProperties.ClusterServicePlanExternalName {
+		servicePlan.Spec.ExternalID == instance.Status.ExternalProperties.ClusterServicePlanExternalID {
```
Comment (pmorie) [inline pkg/controller/controller_instance.go]: It's not clear to me why this needs to change.

File: pkg/controller/controller_instance.go [hunk 2]
```diff
@@ -799,9 +825,9 @@ func (c *controller) reconcileServiceInstance(instance *v1beta1.ServiceInstance)
 			ServiceID:           serviceClass.Spec.ExternalID,
 			OriginatingIdentity: originatingIdentity,
 		}
-		// Only send the plan ID if the plan name has changed from what the Broker has
+		// Only send the plan ID if the plan ID has changed from what the Broker has
 		if toUpdate.Status.ExternalProperties == nil ||
-			toUpdate.Status.InProgressProperties.ClusterServicePlanExternalName != toUpdate.Status.ExternalProperties.ClusterServicePlanExternalName {
+			servicePlan.Spec.ExternalID != toUpdate.Status.ExternalProperties.ClusterServicePlanExternalID {
```
Comment (pmorie) [inline pkg/controller/controller_instance.go]: Nice catch 👏

File: pkg/apis/servicecatalog/validation/instance.go [hunk 3]
```diff
@@ -185,6 +185,14 @@ func validateServiceInstanceStatus(status *sc.ServiceInstanceStatus, fldPath *fi
 func validateServiceInstancePropertiesState(propertiesState *sc.ServiceInstancePropertiesState, fldPath *field.Path, create bool) field.ErrorList {
```
Comment (pmorie) [inline pkg/apis/servicecatalog/validation/instance.go]: I think we should add a validation that ensures that if one of these fields are set, they both are.

Comment (staebler) [reply pkg/apis/servicecatalog/validation/instance.go]: The both need to be set always. That is what the validation that I added does.

File: pkg/controller/controller_instance.go (hunk 1 above)
Comment (staebler) [reply pkg/controller/controller_instance.go]: It doesn't strictly *need* to change. The External ID of a plan does not change, whereas the External Name of a plan can. So if we rely on comparing the External Names, then we have the potential to send the Plan ID in the update request even when the plan is not changing. If we check the External ID instead, then we will inoculate the check from spurious plan name changes.

Example:
1) Instance is created for plan 1 with name A.
2) Plan 1 has a name change from A to B.
3) After a broker relist, service catalog gets the new name of the plan and changes the external name in the ClusterServicePlan.
4) Instance is updated with new parameters.
5) Controller see that the external plan name stored in ExternalProperties differs from the external plan name from ClusterServicePlan. The Plan ID, which is still 1, is sent with the update request.

Comment (staebler) [reply pkg/controller/controller_instance.go]: We use the external plan name currently because that is all we have in ExternalProperties. If the external plan ID have been in ExternalProperties from the start, I would have written the code at that time to use the external plan ID.

Comment (pmorie) [reply pkg/controller/controller_instance.go]: Good point

File: pkg/apis/servicecatalog/validation/instance.go (hunk 3 above)
Comment (pmorie) [reply pkg/apis/servicecatalog/validation/instance.go]: Ack, I somehow misread that.

**Comment by n3wscott** [comment]
LGTM
