### PR TITLE
handle instance deletion that occurs during async provisioning or async update (#1587)

### LINKED ISSUE #1587: Deleting a ServiceInstance or ServiceBinding while async operation in progress fails
When an async operation is in progress for a ServiceInstance or ServiceBinding, the Controller prioritizes polling the last operation over deleting the resource. If the async operation completes after the user has deleted the resource, then the reconciled generation will get set to the incorrect generation--that being the generation after the delete instead of the generation before the delete. When the Controller attempts to update the status of the resource to set the current operation to deprovision or unbind, the update will be rejected by the API Server because a current operation cannot be set when the reconciled generation equals the current generation.

Here is an integration test that fails but should succeed.
```
func TestServiceInstanceDeleteWithAsyncOperationInProgress(t *testing.T) {
	ct := controllerTest{
		t:                            t,
		broker:                       getTestBroker(),
		instance:                     getTestInstance(),
		skipVerifyingInstanceSuccess: true,
		setup: func(ct *controllerTest) {
			ct.osbClient.ProvisionReaction.(*fakeosb.ProvisionReaction).Response.Async = true
			ct.osbClient.PollLastOperationReaction = &fakeosb.PollLastOperationReaction{
				Response: &osb.LastOperationResponse{
					State: osb.StateInProgress,
				},
			}
		},
	}
	ct.run(func(ct *controllerTest) {
		if err := util.WaitForInstanceCondition(ct.client, ct.instance.Namespace, ct.instance.Name,
			v1beta1.ServiceInstanceCondition{
				Type:   v1beta1.ServiceInstanceConditionReady,
				Status: v1beta1.ConditionFalse,
				Reason: "Provisioning",
			}); err != nil {
			t.Fatalf("error waiting for instance to be provisioning asynchronously: %v", err)
		}
		if err := ct.client.ServiceInstances(ct.instance.Namespace).Delete(ct.instance.Name, &metav1.DeleteOptions{}); err != nil {
			t.Fatalf("failed to delete instance: %v", err)
		}
		ct.osbClient.PollLastOperationReaction = &fakeosb.PollLastOperationReaction{
			Response: &osb.LastOperationResponse{
				State: osb.StateSucceeded,
			},
		}
		if err := util.WaitForInstanceToNotExist(ct.client, ct.instance.Namespace, ct.instance.Name); err != nil {
			t.Fatalf("error waiting for instance to not exist: %v", err)
		}
	})
}
```

### PR DESCRIPTION
**Pull request by jboyd01**
partially fixes #1587  (this only covers deleting an Instance during provisioning or update, it does not deal with async service bindings).  I'll do the bindings in a follow up.

Don't bump the ReconciledGeneration after async provisioning or update of an instance if there is a pending deletion.

### CODE REVIEW

**Comment by staebler** [comment]
@jboyd01 Don't we need to do the same thing for async updating?

File: test/integration/controller_test.go [hunk 1]
```diff
@@ -358,6 +358,49 @@ func TestAsyncProvisionWithMultiplePolls(t *testing.T) {
...
+				Status: v1beta1.ConditionFalse,
+				Reason: "Provisioning",
+			}); err != nil {
+			t.Fatalf("error waiting for instance to be provisioning asynchronously: %v", err)
+		}
+
+		if err := ct.client.ServiceInstances(ct.instance.Namespace).Delete(ct.instance.Name, &metav1.DeleteOptions{}); err != nil {
+			t.Fatalf("failed to delete instance: %v", err)
+		}
+		ct.osbClient.PollLastOperationReaction = &fakeosb.PollLastOperationReaction{
```
Comment (staebler) [inline test/integration/controller_test.go]: You cannot change the OSB client reactions while there are reconciliations that could be running. In general, don't change the reactions outside of setup. If the response needs to be dynamic, use a `DynamicPollLastOperationReaction`.

**Comment by jboyd01** [comment]
@staebler thanks for the review and slack discussion.  I agree with your points, I've got some updates here, but more is needed.  Marking as a work in progress

File: pkg/controller/controller_instance.go [hunk 2]
```diff
@@ -1434,8 +1434,16 @@ func (c *controller) processProvisionSuccess(instance *v1beta1.ServiceInstance,
 	setServiceInstanceDashboardURL(instance, dashboardURL)
 	setServiceInstanceCondition(instance, v1beta1.ServiceInstanceConditionReady, v1beta1.ConditionTrue, successProvisionReason, successProvisionMessage)
 	instance.Status.ExternalProperties = instance.Status.InProgressProperties
+	currentReconciledGeneration := instance.Status.ReconciledGeneration
 	clearServiceInstanceCurrentOperation(instance)
 
+	if instance.DeletionTimestamp != nil {
```
Comment (pmorie) [inline pkg/controller/controller_instance.go]: I think this is a fine workaround for now but I do think that we should consider, as a follow-up to this, storing the generation that the in-progress operation is for, so that when we complete an operation we can set the reconciled generation correctly to the generation that started the operation.

File: test/integration/controller_test.go [hunk 3]
```diff
@@ -358,6 +358,171 @@ func TestAsyncProvisionWithMultiplePolls(t *testing.T) {
...
+				if err := util.WaitForInstanceCondition(ct.client, ct.instance.Namespace, ct.instance.Name,
+					v1beta1.ServiceInstanceCondition{
+						Type:   v1beta1.ServiceInstanceConditionReady,
+						Status: v1beta1.ConditionFalse,
+						Reason: "UpdatingInstance",
+					}); err != nil {
+					t.Fatalf("error waiting for instance to be updating asynchronously: %v", err)
+				}
+
+				if err := ct.client.ServiceInstances(ct.instance.Namespace).Delete(ct.instance.Name, &metav1.DeleteOptions{}); err != nil {
```
Comment (kibbles-n-bytes) [inline test/integration/controller_test.go]: I believe there's a race here between the update completing and the deletion timestamp getting set. Instead of basing the response of the last operation on the number of polls that occurred, I think we should use a boolean (`shouldFinishPolling`?) that we toggle from false to true after issuing the delete request.

Comment (staebler) [reply test/integration/controller_test.go]: I concur with @kibbles-n-bytes on this. So that it's clear, the same race exists in the other test.

**Comment by jboyd01** [comment]
Thanks for the reviews.  Good point and that makes a much better test @kibbles-n-bytes, @staebler, thanks.  I've updated both tests.

File: test/integration/controller_test.go [hunk 4]
```diff
@@ -358,6 +358,181 @@ func TestAsyncProvisionWithMultiplePolls(t *testing.T) {
...
+				instance:                     getTestInstance(),
+				skipVerifyingInstanceSuccess: true,
+				setup: func(ct *controllerTest) {
+					ct.osbClient.ProvisionReaction.(*fakeosb.ProvisionReaction).Response.Async = true
+					ct.osbClient.PollLastOperationReaction = fakeosb.DynamicPollLastOperationReaction(
+						func(_ *osb.LastOperationRequest) (*osb.LastOperationResponse, error) {
+							state := osb.StateInProgress
+							select {
+							// nonblocking check for a message to finish async provisioning, return inProgress otherwise
+							case <-done:
```
Comment (kibbles-n-bytes) [inline test/integration/controller_test.go]: There might still be a race here. If a reconciliation starts, and then the deletion timestamp is set, we'd pull `true` out of `done` but then fail to update the instance (as our resource is out of date). The next reconciliation loop, we'd then be back to the channel being empty.

I think a better gauge would be if the channel is closed or not.

Comment (jboyd01) [reply test/integration/controller_test.go]: @kibbles-n-bytes, are you ok with instead moving the declaration and initialization of ```state := osb.StateInProgress```  up to the top of the Run() ?  This way reading from the channel toggles us to a done state and we stay there for any additional polls.

Comment (staebler) [reply test/integration/controller_test.go]: What about using an atomic int instead of a channel at all? I think that makes it clearer what is going on from a readability standpoint.

File: pkg/controller/controller_instance.go (hunk 2 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: Agreed, we should store a correct `reconciledGeneration` 😀

Comment (nilebox) [reply pkg/controller/controller_instance.go]: @jboyd01 leave a TODO then?

File: pkg/controller/controller_instance.go [hunk 5]
```diff
@@ -1474,6 +1483,13 @@ func (c *controller) processProvisionFailure(instance *v1beta1.ServiceInstance,
 		err = fmt.Errorf(failedCond.Message)
 	} else {
 		clearServiceInstanceCurrentOperation(instance)
+
+		if instance.DeletionTimestamp != nil {
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: could you extract this code to a separate method instead of copy-pasting? it will make a cleanup in a follow-up PR much easier.
