### PR TITLE
Clear orphan mitigation when deleted by user

### LINKED ISSUE #1482: ServiceInstance or ServiceBinding deleted during on-going Provision or Bind operation behaves incorrectly
When a ServiceInstance or ServiceBinding resource is deleted while there is an on-going Provision or Bind operation, the Status of the resource is placed in an incorrect state. The `CurrentOperation` remains `Provision` or `Bind` even though the current operation is actually `Deprovision` or `Unbind`. This causes problems if the new operation is async because the async polling relies on `CurrentOperation` being correct. Additionally, the `OperationStartTime` is not restarted.

### PR DESCRIPTION
**Pull request by staebler**
Fixes #1482.

Exit orphan mitigation when the resource is being deleted.

### CODE REVIEW

File: pkg/controller/controller_binding_test.go [hunk 1]
```diff
@@ -2444,7 +2444,8 @@ func TestReconcileBindingWithOrphanMitigationReconciliationRetryTimeOut(t *testi
 			SecretName:         testServiceBindingSecretName,
 		},
 	}
-	startTime := metav1.NewTime(time.Now().Add(-7 * 24 * time.Hour))
+	startTime := metav1.NewTime(time.Now().Add(-1 * time.Hour))
```
Comment (kibbles-n-bytes) [inline pkg/controller/controller_binding_test.go]: This test was meant to check the reconciler's reaction to a binding currently undergoing orphan mitigation whose retry duration has been exceeded. We should have a different test that checks this situation.

Comment (staebler) [reply pkg/controller/controller_binding_test.go]: It wasn't clear to me what the test was actually testing. Because the binding did not have a Current person set, it wasn't actually testing the scenario of reconciliation timing out. The OperationStartTime was being set to Now by the controller. I tried to deduce by the check that the reconcile function was expected to return an error that the test was supposed to test what happened when the result of the deprovision request was a timeout error.

**Comment by nilebox** [comment]
LGTM.

File: pkg/controller/controller_binding_test.go (hunk 1 above)
Comment (kibbles-n-bytes) [reply pkg/controller/controller_binding_test.go]: Ah, okay. Looks like the intent of the test was to test the logic where an error during an orphan mitigation unbind when the retry duration has been exceeded gets us into the logic [here](https://github.com/staebler/service-catalog/blob/18b655c6cbe9d33b7792767792f3c23015953435/pkg/controller/controller_binding.go#L735). However, the test isn't actually checking for that; it's just verifying the normal orphan mitigation reconciliation error state, and that's why fixing the `CurrentOperation` bug made it actually start to fail, and setting the `OperationStartTime` to something sooner made it start to pass.

I'm fine with putting a bandaid on it for now and fixing it later.

**Comment by kibbles-n-bytes** [comment]
@staebler agreed to follow-up with fixing the test in question and adding more unit tests. I feel fine merging this now.
