### PR TITLE
4xx, 5xx and Connection timeout should be retriable (not terminal errors)

### LINKED ISSUE #1715: Instances: 4xx, 5xx and Connection timeout should be retriable (not terminal errors)
If the OSB request to the broker times out, Service Catalog executes the orphan mitigation and leaves the instance in the TerminalError status:
```
      message: 'readiness check failed: ErrorCallingProvision: Communication with
        the ClusterServiceBroker timed out; operation will not be retried: Put https://example.com/v2/service_instances/e00dfeb3-a3ce-4ec2
-b2bb-8f1232cc48cc?accepts_incomplete=true:
        net/http: request canceled (Client.Timeout exceeded while awaiting headers)'
      reason: TerminalError
      status: "True"
      type: Error
```
It means that if OSB broker was temporarily unavailable (or had some other temporary issue leading to slow request processing), Service Catalog won't retry provisioning. So to retry, the user needs to whether delete the instance and create it again, or mutate the spec (`updateRequest++`).

It's probably not the best UX. Shall we retry a certain number of times before giving up?

P.S. The scope of this issue is bigger, i.e. it also applies to 4xx and 5xx errors (with orphan mitigation required or without). The Kubernetes way of handling errors is to retry after failures (with exponential backoff).

### PR DESCRIPTION
**Pull request by nilebox**
Fixes #1715 

The final, third part (item `1.`) of the TODO list https://github.com/kubernetes-incubator/service-catalog/issues/1715#issuecomment-366857230
item `2.`: #1751
item `3.`: #1748

### CODE REVIEW

File: pkg/controller/controller_instance.go [hunk 1]
```diff
@@ -1457,35 +1466,52 @@ func (c *controller) processProvisionSuccess(instance *v1beta1.ServiceInstance,
...
+		resetServiceInstanceCondition(instance, v1beta1.ServiceInstanceConditionFailed)
+		errorMessage = fmt.Errorf(readyCond.Message)
+	}
 
-	// Need to vary return error depending on whether the worker should
-	// requeue this resource.
-	var err error
 	if shouldMitigateOrphan {
+		// TODO nilebox: if failedCond == nil, we lose the original error reason/message
+		// in the status completely there. Should we keep the original reason/message instead?
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: I propose that we add a new OrphanMitigation condition that is true when the instance is undergoing orphan mitigation. The Ready condition is not changed when starting and stopping orphan mitigation. Presumably, the Ready condition will already be false when orphan mitigation starts. Although I'd also be fine with relying solely on `OrphanMitigiationInProgress` instead of adding a new condition. Either way, I suggest that we stop changing the Ready condition with the starting orphan mitigation reason. Of course, this is all follow-on work.

File: pkg/controller/controller_instance.go [hunk 2]
```diff
@@ -1457,35 +1466,52 @@ func (c *controller) processProvisionSuccess(instance *v1beta1.ServiceInstance,
...
 
-	c.recorder.Event(instance, corev1.EventTypeWarning, failedCond.Reason, failedCond.Message)
-	setServiceInstanceCondition(instance, v1beta1.ServiceInstanceConditionFailed, failedCond.Status, failedCond.Reason, failedCond.Message)
+	var errorMessage error
+	if failedCond != nil {
+		c.recorder.Event(instance, corev1.EventTypeWarning, failedCond.Reason, failedCond.Message)
+		setServiceInstanceCondition(instance, v1beta1.ServiceInstanceConditionFailed, failedCond.Status, failedCond.Reason, failedCond.Message)
+		errorMessage = fmt.Errorf(failedCond.Message)
+	} else {
+		resetServiceInstanceCondition(instance, v1beta1.ServiceInstanceConditionFailed)
```
Comment (staebler) [inline pkg/controller/controller_instance.go]: Why is resetting the Failed condition part of processing a failure? The Failed condition should be cleared out as part of starting a new provision rather than as part of finishing a provision. As it is, the Failed condition is not cleared out when the provision is successful.

File: pkg/controller/controller.go [hunk 3]
```diff
@@ -631,10 +631,15 @@ func shouldStartOrphanMitigation(statusCode int) bool {
 	is5XX := (statusCode >= 500 && statusCode < 600)
 
 	return (is2XX && statusCode != http.StatusOK) ||
-		statusCode == http.StatusRequestTimeout ||
 		is5XX
 }
 
+// isTerminalHttpStatus returns whether an error with the given HTTP status
```
Comment (nilebox) [inline pkg/controller/controller.go]: nit: `s/isTerminalHttpStatus/isRetriableHTTPStatus`

File: pkg/controller/controller_instance.go (hunk 2 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: The `failedCond == nil` here means that we have encountered a retriable error (see the `processTemporaryProvisionFailure` method).
The `Failed:True` condition along with the latest `ObservedGeneration` means: "terminal failure that doesn't need retrying until the spec is updated (and consequently the Generation is incremented)".

As a reminder from #1748:
```go
+// isServiceInstanceProcessedAlready returns true if there is no further processing
+// needed for the instance based on ObservedGeneration
+func isServiceInstanceProcessedAlready(instance *v1beta1.ServiceInstance) bool {
+	return instance.Status.ObservedGeneration >= instance.Generation &&
+		(isServiceInstanceReady(instance) || isServiceInstanceFailed(instance)) && !instance.Status.OrphanMitigationInProgress
+}
```
The `isServiceInstanceProcessedAlready` is invoked before we start a new provisioning operation, and it will return `true` unless we clear the reset the `Failed` condition as I do there.

I don't like that this also means that we lose the `reason` and `message` there, but currently we store the same reason and message in the `Ready` condition, so it's probably not too bad.

File: pkg/controller/controller_instance.go (hunk 1 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: @staebler I personally don't have objection against OrphanMitigation condition, we can discuss this separately with @pmorie and others.
As you suggest (and as my TODO suggests too), I will keep the original reason/message for now, and probably leave a TODO that it would be nice to somehow reflect the started orphan mitigation in the status somehow.

Comment (nilebox) [reply pkg/controller/controller_instance.go]: Raised an issue #1771 to discuss this.

File: pkg/controller/controller_instance.go [hunk 4]
```diff
@@ -1495,7 +1521,12 @@ func (c *controller) processProvisionFailure(instance *v1beta1.ServiceInstance,
 		return err
 	}
 
-	return err
+	// Need to vary return error depending on whether the worker should
+	// requeue this resource.
+	if failedCond == nil || shouldMitigateOrphan {
+		return errorMessage
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: This is not strictly required as we have updated the status above, so the instance will come back to the queue anyway.
Keeping it as it is, as it was written that way before.

**Comment by nilebox** [comment]
> 1. What is the desired behavior when orphan mitigation fails? In that case, are we going to consider the instance dead and unusable? Or are we going to open the instance up for request retries and processing spec updates?

@staebler I think it should be unusable, but could possibly be manually triggered again by `updateRequests++`?

The spec says that the platform SHOULD (i.e. not MUST) keep trying until it succeeds (nothing about time limits or max number of retries):
> the Platform SHOULD attempt to delete resources it cannot be sure were successfully created, and SHOULD keep trying to delete them until the Service Broker responds with a success.

Also I love this OSB spec paragraph:
> If the Platform encounters an internal error provisioning a Service Instance or Service Binding (for example, saving to the database fails), then it MUST at least send a single delete or unbind request to the Service Broker to prevent the creation of an orphan.

It sounds like "best effort but no guarantees whatsoever". Just brilliant.
We can discuss this at the next SIG call.

**Comment by nilebox** [comment]
> 2. Retryable requests will restart the OperationStartTime when the orphan mitigation completes. This means that retryable requests involving orphan mitigation have the potential to retry indefinitely.

@staebler Yes. Is this bad? That's how Kubernetes works - it keeps trying to deploy a Pod even if the Docker image doesn't exist in DockerHub. There might be some bug on the broker side leading to `500 Internal Server Error` that can be fixed at any time, so it makes sense to keep retrying to provision.

I think there should be some monitoring tool that would cleanup all the instances that have been stuck in provisioning for too long and/or notify users (owners) about this issue (i.e. OpenShift and Atlassian will probably have something in-house in that area). But that's out of scope of Service Catalog.

If such behavior turns out to be painful, we can fix it later by introducing some retry limits probably.

**Comment by nilebox** [comment]
> I think it should be unusable (but not dead), but could possibly be manually triggered again by updateRequests++?

Also need to check whether the `OrphanMitigationInProgress` is kept after exceeding the retry timeout. I suspect that we reset it, and we might need an `OrphanMitigation` condition to be able to keep it.

**Comment by staebler** [comment]
> > Retryable requests will restart the OperationStartTime when the orphan mitigation completes. This means that retryable requests involving orphan mitigation have the potential to retry indefinitely.

> @staebler Yes. Is this bad? That's how Kubernetes works - it keeps trying to deploy a Pod even if the Docker image doesn't exist in DockerHub. There might be some bug on the broker side leading to 500 Internal Server Error that can be fixed at any time, so it makes sense to keep retrying to provision.

Service catalog specifically has the reconciliation retry duration that determines how long reconciliation of a given generation should be attempted before giving up. Let's say that the provision request failed repeatedly with 408 Request Timeout errors. By default, the controller would stop attempting to send provision requests to the broker after 7 days. At that point, the controller would set the instance to `Failed:True`. On the other hand, let's say that the provision request failed repeatedly with 500 Internal Server Error errors. In that case, the controller will perform orphan mitigation after each error. Each successful orphan mitigation will reset the `OperationStartTime` for the instance. Consequently, the controller will send provision requests indefinitely, beyond the 7-day limit. There should not be a difference in how long the controller attempts reconciliation between errors that require orphan mitigation and errors that do not.

**Comment by staebler** [comment]
> >What is the desired behavior when orphan mitigation fails? In that case, are we going to consider the instance dead and unusable? Or are we going to open the instance up for request retries and processing spec updates?

> @staebler You mean when we reached the retry timeout reconciliationRetryDurationExceeded(instance.Status.OperationStartTime)? I think it should be unusable (but not dead), but could possibly be manually triggered again by updateRequests++?

@nilebox Yes, that looks to be the only (non-constraint-breaking) reason why an orphan mitigation would fail.

I think that we have some inconsistencies in how we are treating broker resources if we allow further provision requests after a failed orphan mitigation. If a pure delete fails (ie, exceeds reconciliation retry duration), then the instance is kept around so that the user may take manual actions to negotiate with the broker to clean up resources. For a failed orphan mitigation, we would not be giving the user the same opportunity for manual intervention.

**Comment by nilebox** [comment]
> Each successful orphan mitigation will reset the OperationStartTime for the instance. Consequently, the controller will send provision requests indefinitely, beyond the 7-day limit.

Ok, I see the problem now. The easiest solution then is not to invoke the `recordStartOfServiceInstanceOperation()` method in case of deletion (or at least for orphan mitigation)?

**Comment by nilebox** [comment]
> For a failed orphan mitigation, we would not be giving the user the same opportunity for manual intervention.

@staebler I think we should keep the instance in the `unusable` state if orphan mitigation retry limit is exceeded.
By "but could possibly be manually triggered again by updateRequests++" I meant that it should trigger the new cycle of orphan mitigation, not the provisioning.

This would allow for manual intervention:
1. Orphan mitigation fails until retry limit is exceeded, we mark the status with `Failed:True` condition and stop retrying.
2. User reports about this issue to the broker developer, and the bugfix is released. Broker is now ready to process the orphan mitigation correctly.
3. User updates the spec (e.g. `updateRequests++`), and triggers the reconciliation loop. Service Catalog controller sees that there is unfinished orphan mitigation ([#1771 (comment)](https://github.com/kubernetes-incubator/service-catalog/issues/1771#issuecomment-369104345)), and starts it again.
4. Orphan mitigation has successfully finished, and now there will be a new provisioning operation with updated spec.

**Comment by kibbles-n-bytes** [comment]
@staebler @nilebox Perhaps this is a situation in which it'd be beneficial to use the `LastTransitionTime` of the new `OrphanMitigationCondition`? From a purity standpoint, the "operation" that is in progress here is a Provision, so the operation's start time should not _really_ be reset when we start orphan mitigating. However, we could gauge how long the orphan mitigation has been ongoing based off of the last time our `OrphanMitigationCondition` transitioned from `False`/`Unknown` (implicit when condition not present) to `True`.

Would complicate the logic of the controller slightly, but I think it'd get us the desired behavior.

**Comment by nilebox** [comment]
@kibbles-n-bytes your solution won't work in the case when we exhausted the retry timeout, but then the spec was updated (leading to `Generation++`) which should trigger another round of orphan mitigation with a new `LastTransitionTime = Now`. So we need to explicitly reset the "operation start time" every time we start a new round of orphan mitigation, static time can't solve this problem.

**Comment by nilebox** [comment]
@kibbles-n-bytes @staebler how about adding a new operation type `CurrentOperation=OrphanMitigation`? This would make `OperationStartTime` reflect a single orphan mitigation operation (and we would also lose the start time of `Provision` operation, but that's probably fine). `OrphanMitigation` should always be followed by a new `Provisioning` operation, so there is no ambiguity.

Combined with the `OrphanMitigation` condition and `OrphanMitigationInProgress` flag it gets ridiculous though, so I'm not proposing this option seriously, just throwing out another idea.

**Comment by nilebox** [comment]
Actually nevermind, I lost the context of discussion :(
As it was pointed before we don't want to reset the `OperationStartTime` to avoid retrying indefinitely.

**Comment by nilebox** [comment]
@staebler @kibbles-n-bytes rebased on the latest mater after merged other `non-happy-path` PRs, please review.

> Each successful orphan mitigation will reset the OperationStartTime for the instance. Consequently, the controller will send provision requests indefinitely, beyond the 7-day limit. 

@staebler we don't do that anymore (merged in the other PR) - we don't invoke `recordStartOfServiceInstanceOperation` for orphan mitigation anymore.

File: pkg/controller/controller.go [hunk 5]
```diff
@@ -664,10 +664,15 @@ func shouldStartOrphanMitigation(statusCode int) bool {
...
 
 	return (is2XX && statusCode != http.StatusOK) ||
-		statusCode == http.StatusRequestTimeout ||
 		is5XX
 }
 
+// isRetriableHTTPStatus returns whether an error with the given HTTP status
+// code is retriable.
+func isRetriableHTTPStatus(statusCode int) bool {
+	return statusCode != 400
```
Comment (ash2k) [inline pkg/controller/controller.go]: FYI there are constants for HTTP status codes in the `http` package

File: pkg/controller/controller_instance.go (hunk 4 above)
Comment (nilebox) [reply pkg/controller/controller_instance.go]: Actually this is needed but the comment is misleading. We need to prevent resetting the rate limiter.
/cc @kibbles-n-bytes this is another place where we claim that we want to requeue the resource when what we really need is to prevent invoking the `Forget()` method.
I will update the comment.

File: pkg/controller/controller_instance.go [hunk 6]
```diff
@@ -1662,12 +1681,14 @@ func (c *controller) processUpdateServiceInstanceSuccess(instance *v1beta1.Servi
 // processUpdateServiceInstanceFailure handles the logging and updating of a
 // ServiceInstance that hit a terminal failure during update reconciliation.
 func (c *controller) processUpdateServiceInstanceFailure(instance *v1beta1.ServiceInstance, readyCond, failedCond *v1beta1.ServiceInstanceCondition) error {
+	// TODO nilebox: We need to distinguish terminal and temporary errors there
+	// but we need to merge https://github.com/kubernetes-incubator/service-catalog/pull/1748
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: #1748 is merged, so we can fix this TODO

File: pkg/controller/controller_instance.go [hunk 7]
```diff
@@ -1606,24 +1625,35 @@ func (c *controller) processProvisionFailure(instance *v1beta1.ServiceInstance,
...
 		// error that doesn't require orphan mitigation
 		instance.Status.DeprovisionStatus = v1beta1.ServiceInstanceDeprovisionStatusNotRequired
-		instance.Status.ReconciledGeneration = instance.Status.ObservedGeneration
+	}
+
+	if failedCond == nil || shouldMitigateOrphan {
+		// Don't reset the current operation if the error is retriable
+		// or requires an orphan mitigation.
+		// Only reset the OSB operation status
+		clearServiceInstanceAsyncOsbOperation(instance)
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: @kibbles-n-bytes note that I am reusing your newly introduced method there and in the update failure handling too.
Please double check if this is a correct behavior.
The goal here is to keep the `OperationStartTime` untouched to avoid retrying indefinitely.

File: pkg/controller/controller_instance.go [hunk 8]
```diff
@@ -1606,24 +1625,35 @@ func (c *controller) processProvisionFailure(instance *v1beta1.ServiceInstance,
...
 		return err
 	}
 
-	return err
+	// The instance will be requeued in any case, since we updated the status
+	// a few lines above.
+	// But we still need to return a non-nil error for retriable errors and
+	// orphan mitigation to avoid resetting the rate limiter.
+	if failedCond == nil || shouldMitigateOrphan {
+		return errorMessage
```
Comment (nilebox) [inline pkg/controller/controller_instance.go]: See the comment above that clarifies why do we need to return a non-nil error.

File: pkg/controller/controller_instance.go (hunk 7 above)
Comment (arschles) [reply pkg/controller/controller_instance.go]: the idea behind this seems ok to me

Comment (kibbles-n-bytes) [reply pkg/controller/controller_instance.go]: @nilebox As a consequence of this, it seems like we'll be only trying the deprovision once in the case of a final orphan mitigation after a reconciliation retry duration timeout during a provision. For now, I think it's fine, though we should re-look at it in the future.

**Comment by kibbles-n-bytes** [comment]
@nilebox Just to be sure, neither this nor #1789 add logic that re-triggers orphan mitigation after it has already failed, if someone edits the spec. Correct? So resources that failed orphan mitigation are stuck in a permanent failed state. If so, I'm okay with that, and we can revisit it later.

**Comment by kibbles-n-bytes** [comment]
LGTM. RIP everyone wishing to fix the resources after they've fat-fingered a parameter, though. :skull: Making `400 Bad Request` a terminal failure will help with that, but retrying async operations could still get us in a sticky situation. I'm okay with it going in, but we gotta fix that ASAP. Until then, though, users can modify the default reconciliation retry duration via the `--reconciliation-retry-duration` parameter on the controller-manager binary.

**Comment by kibbles-n-bytes** [comment]
Retriggering Jenkins just for peace of mind. If it's green, please merge.

**Comment by pmorie** [comment]
> RIP everyone wishing to fix the resources after they've fat-fingered a parameter, though

Let's not introduce a regression here - people already have issues with recovering from a change to a bad parameter state.

Can you describe the situation you're talking about?

**Comment by nilebox** [comment]
> Just to be sure, neither this nor #1789 add logic that re-triggers orphan mitigation after it has already failed, if someone edits the spec, correct? So resources that failed orphan mitigation are stuck in a permanent failed state.

@kibbles-n-bytes  Nope. Orphan mitigation will be retried for a week (by default). And if the max retry duration is exceeded, we will stop retrying. But after the spec is updated, it will trigger orphan mitigation, followed by reconciling a new spec.

If you disagree with this behavior, or think that the code behaves differently, please comment.

**Comment by nilebox** [comment]
> Let's not introduce a regression here - people already have issues with recovering from a change to a bad parameter state.

@pmorie just to be clear here: currently people have **no way** of recovering from a change to a bad parameter state at all.
This PR adds support for:
1. retry loop after any failure except `400 Bad Request`
2. orphan mitigation and reconciliation after spec is updated.

So it's alone a huge improvement. And there could not be a regression for behavior which was missing before.

On the other hand, and that's what @kibbles-n-bytes is referring too, the retry loop also makes #1755 more obviously annoying for non-happy-path: the spec will be locked for a week if OSB broker continuously returns an error on provisioning (any error code except `400 Bad Request`). 

I definitely agree that we need to fix #1755 ASAP, and that's why I have been pushing for it for weeks now.

**Comment by nilebox** [comment]
> So resources that failed orphan mitigation are stuck in a permanent failed state.

@kibbles-n-bytes ah sorry, you mean the ones that are already marked with the terminal `Failed` condition (before this change)? They won't automatically recover, yes, but after the spec is updated, it should trigger orphan mitigation (I think) and reconciling the new spec. There's no more dead end terminal error state for instances, so we should be able to recover from any state after updating Service Catalog (apart from `DeletionTimestamp != nil`).

**Comment by duglin** [comment]
Let's be clear though, we could remove the lock for the "same user" to unblock most people and not have any concern about OSB API spec violations. That would be an easy fix (I think), that could probably be done ( by someone who knows the code) in short order.

**Comment by nilebox** [comment]
@duglin what I meant to say is that current behavior is unacceptable. One way or another, we need to fix that ASAP to whatever we all agree to.

**Comment by duglin** [comment]
yes but my point is that the urgency of this can be GREATLY diminished if we would just unlock it for the same user. That would give us time to make the right design decision (for kube and osbapi compliance) and not make a rushed one.

I doubt this would take more than a few lines of code to do - it should just require a modification to the lock check to add something like `request.UserInfo != instance.UserInfo`

File: pkg/controller/controller_instance.go [hunk 9]
```diff
@@ -761,14 +769,12 @@ func (c *controller) pollServiceInstance(instance *v1beta1.ServiceInstance) erro
 			reason := errorProvisionCallFailedReason
 			message := "Provision call failed: " + description
 			readyCond := newServiceInstanceReadyCondition(v1beta1.ConditionFalse, reason, message)
-			failedCond := newServiceInstanceFailedCondition(v1beta1.ConditionTrue, reason, message)
-			err = c.processProvisionFailure(instance, readyCond, failedCond, false)
+			err = c.processTemporaryProvisionFailure(instance, readyCond, false)
```
Comment (n3wscott) [inline pkg/controller/controller_instance.go]: This introduced a bug where if the polling operation returns `state=failed`, in combo with the change on this line: https://github.com/kubernetes-incubator/service-catalog/blob/e15b73719911853d3755b71f3d8b26b21296d0a3/pkg/controller/controller_instance.go#L1652

causes a failed provision after polling to never attempt deprovision.

Comment (nilebox) [reply pkg/controller/controller_instance.go]: @n3wscott apologies, this is because I thought that for async operations we never need to perform an orphan mitigation.
If what @kibbles-n-bytes wrote about bindings in https://github.com/openservicebrokerapi/servicebroker/pull/334#issuecomment-375496515 is true about instances too, then we could just change a flag to `true` there:
```go
err = c.processTemporaryProvisionFailure(instance, readyCond, true)
```
i.e. perform orphan mitigation immediately instead of waiting for deletion of the instance.
Thoughts?

@n3wscott also, can you create an issue to track this?

Comment (n3wscott) [reply pkg/controller/controller_instance.go]: I had: https://github.com/kubernetes-incubator/service-catalog/issues/1879
