### PR TITLE
Fixed bug where all plans of a service would have the same description

### LINKED ISSUE #742: Wrong plan description comes back when a service class has multiple plans
I made some local changes to the UPS service metadata:

https://github.com/spadgett/service-catalog/commit/ad7f302d469d8968f81148cec9e0b73db8ee2c21

When I get the service classes back from the catalog, the first plan uses the wrong description. It should be "The default user provided service plan."

```json
      "plans": [
        {
          "name": "default",
          "description": "An alternate plan for testing, which is no different from the default.",
          "osbGuid": "86064792-7ea2-467b-af93-ac9694d96d52",
          "osbFree": true,
          "osbMetadata": null
        },
        {
          "name": "alternate",
          "description": "An alternate plan for testing, which is no different from the default.",
          "osbGuid": "9b67a0e4-26d1-11e7-93ae-92361f002671",
          "osbFree": true,
          "osbMetadata": null
        }
      ]
```

Here is the full JSON response:

```json
{
  "kind": "ServiceClassList",
  "apiVersion": "servicecatalog.k8s.io/v1alpha1",
  "metadata": {
    "selfLink": "/apis/servicecatalog.k8s.io/v1alpha1/serviceclasses",
    "resourceVersion": "12"
  },
  "items": [
    {
      "metadata": {
        "name": "user-provided-service",
        "selfLink": "/apis/servicecatalog.k8s.io/v1alpha1/serviceclassesuser-provided-service",
        "uid": "dd32b96e-2902-11e7-83d7-0242ac110008",
        "resourceVersion": "5",
        "creationTimestamp": "2017-04-24T15:29:53Z"
      },
      "brokerName": "ups-broker",
      "bindable": false,
      "plans": [
        {
          "name": "default",
          "description": "An alternate plan for testing, which is no different from the default.",
          "osbGuid": "86064792-7ea2-467b-af93-ac9694d96d52",
          "osbFree": true,
          "osbMetadata": null
        },
        {
          "name": "alternate",
          "description": "An alternate plan for testing, which is no different from the default.",
          "osbGuid": "9b67a0e4-26d1-11e7-93ae-92361f002671",
          "osbFree": true,
          "osbMetadata": null
        }
      ],
      "planUpdatable": false,
      "osbGuid": "4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468",
      "osbTags": [
        "example",
        "ups"
      ],
      "description": "A sample user provided service (UPS) for demonstrating the Kubernetes Service Catalog. During binding, this broker simply echos the values back that were provided when it was provisioned. The values are the service.",
      "osbMetadata": {
        "displayName": "User Provided Service",
        "documentationUrl": "https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md"
      }
    }
  ]
}
```

cc @pmorie

### PR DESCRIPTION
**Pull request by luksa**
Fixes #742 

Besides adding the test for plan descriptions, I also added a test for service descriptions. Apparently, there's no bug there.

BTW: why is ServicePlan.Description even a pointer?

### CODE REVIEW

**Comment by pmorie** [comment]
Awesome, thanks for the fix @luksa 

> BTW: why is ServicePlan.Description even a pointer?

Optional fields are pointers in k8s APIs.

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -1436,12 +1436,13 @@ func convertCatalog(in *brokerapi.Catalog) ([]*v1alpha1.ServiceClass, error) {
 func convertServicePlans(plans []brokerapi.ServicePlan) ([]v1alpha1.ServicePlan, error) {
 	ret := make([]v1alpha1.ServicePlan, len(plans))
 	for i, plan := range plans {
+		descCopy := string(plan.Description)
```
Comment (pmorie) [inline pkg/controller/controller.go]: go foreach loop strikes again.  Thanks for the fix.
