### PR TITLE
Making TPRs list-able with '--all-namespaces'

### LINKED ISSUE #672: On TPR, list instances does not work
When I create an instance while using TPR as the backend for the API server, I can get that specific instance, but listing instances does not work, even when using the qualified API version and resource name:

```
$ k get instances ups-instance -n test-ns -o yaml                                                                                                                                                                  
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  creationTimestamp: 2017-04-07T20:39:22Z
  finalizers:
  - kubernetes
  name: ups-instance
  namespace: test-ns
  resourceVersion: "8179"
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/namespaces/test-ns/instances/ups-instance
  uid: 48280219-1bd2-11e7-a737-68f728db1985
spec:
  osbGuid: 42354f05-1dac-4ae6-a2ac-382c41fcf218
  planName: default
  serviceClassName: user-provided-service
status:
  conditions: []

$ k get instances --all-namespaces                                                                                                                                                                                 
No resources found.

$ k get Instance.v1alpha1.servicecatalog.k8s.io --all-namespaces
No resources found.
```

### PR DESCRIPTION
**Pull request by arschles**
See the comments in https://github.com/kubernetes-incubator/service-catalog/issues/672#issuecomment-294970242 for details on the problem and this solution.

Requires #715 
Fixes #672

### CODE REVIEW

**Comment by arschles** [comment]
Now, all of the commands listed in #672 work:

```console
ENG000656:service-catalog aaronschlesinger$ k get instances ups-instance -n test-ns -o yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  creationTimestamp: 2017-04-18T20:11:51Z
  finalizers:
  - kubernetes
  name: ups-instance
  namespace: test-ns
  resourceVersion: "178021"
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/namespaces/test-ns/instances/ups-instance
  uid: 4285b6a4-2473-11e7-9609-0800277cda4e
spec:
  osbGuid: 614e812b-519a-459e-a530-e481fa044243
  planName: default
  serviceClassName: user-provided-service
status:
  conditions:
  - lastTransitionTime: 2017-04-18T21:14:47Z
    message: The instance references a ServiceClass that does not exist. Instance
      "test-ns/ups-instance" references a non-existent ServiceClass "user-provided-service"
    reason: ReferencesNonexistentServiceClass
    status: "False"
    type: Ready
ENG000656:service-catalog aaronschlesinger$ k get instances --all-namespaces
NAMESPACE   NAME           KIND
test-ns     ups-instance   Instance.v1alpha1.servicecatalog.k8s.io
ENG000656:service-catalog aaronschlesinger$ k get Instance.v1alpha1.servicecatalog.k8s.io --all-namespaces
NAMESPACE   NAME           KIND
test-ns     ups-instance   Instance.v1alpha1.servicecatalog.k8s.io
```

... when previously only 2/3 of them did.

Note that when a namespaced resource (i.e. an `Instance`) is requested in the same namespace as the server's default TPR namespace, the server behaves in the same way as if `--all-namespaces` was passed to `kubectl`

File: pkg/storage/tpr/storage_interface.go [hunk 1]
```diff
@@ -325,31 +325,52 @@ func (t *store) List(
...
-		ns,
-		t.singularKind.URLName(),
-	)
-
-	var unknown runtime.Unknown
-	if err := req.Do().Into(&unknown); err != nil {
-		glog.Errorf("doing request (%s)", err)
-		return err
+	if t.hasNamespace && ns == t.defaultNamespace {
+		// if the resource is supposed to have a namespace, and the given one is the default,
```
Comment (vaikas-google) [inline pkg/storage/tpr/storage_interface.go]: Is this the behaviour that current objects do?

Comment (arschles) [inline pkg/storage/tpr/storage_interface.go]: do you mean built-in objects?

Comment (vaikas-google) [inline pkg/storage/tpr/storage_interface.go]: yes, that's what I meant, sorry for not being clearer :)

**Comment by vaikas-google** [comment]
Looks like travis failed due to gofmt failing on:
pkg/storage/tpr/list_resources_test.go

**Comment by krancour** [comment]
@arschles... I think you're afk today... I moved this back into an in-progress status as I've had some important revelations about unit testing the tpr-backed storage impl that I think you and I should discuss before we further consider merging either this or #715-- both of which add new unit tests for the tpr-backed storage.

**Comment by pmorie** [comment]
@arschles looks like a gofmt error

**Comment by krancour** [comment]
@arschles following up on my previous comment... I have discussed with @pmorie to confirm my revelation: Our unit tests for tpr-backed storage should be using internal/unversioned types as the inputs and outputs. (irl, the registries are the clients of the storage layer and they wheel and deal in internal/unversioned types.)

File: pkg/storage/tpr/storage_interface.go (hunk 1 above)
Comment (arschles) [inline pkg/storage/tpr/storage_interface.go]: got it. no, this isn't the behavior of built-in objects, because they don't have the concept of a "default namespace" (because they are stored in etcd).

**Comment by arschles** [comment]
@vaikas-google @pmorie the `gofmt` issue is now fixed

@krancour now that #715 is in, I rebased this onto that, and I merged https://github.com/arschles/kubernetes-incubator-service-catalog/pull/3 into this branch, it looks like this is using the proper types. Thanks for pointing that out

File: pkg/storage/tpr/list_resources_test.go [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+	objStorage["broker1"] = &sc.Broker{
+		TypeMeta:   newTypeMeta(kind),
+		ObjectMeta: metav1.ObjectMeta{Name: "broker1"},
+	}
+	objStorage["broker2"] = &sc.Broker{
+		TypeMeta:   newTypeMeta(kind),
+		ObjectMeta: metav1.ObjectMeta{Name: "broker2"},
+	}
+	cl.storage[ns] = newTypedStorage()
+	cl.storage[ns][ServiceBrokerKind.URLName()] = objStorage
```
Comment (krancour) [inline pkg/storage/tpr/list_resources_test.go]: I like this strategy of manipulating the fake's core apiserver client's underlying in-memory storage directly to set up the test. I will adopt that in a follow-up to #715. 👍

File: pkg/storage/tpr/init_test.go [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+	"github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
+	_ "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/install"
+	"github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/testapi"
+	"k8s.io/apimachinery/pkg/runtime/schema"
+	"k8s.io/client-go/pkg/api"
+	_ "k8s.io/client-go/rest"
+)
+
+func serviceCatalogAPIGroup() testapi.TestGroup {
+	// OOPS: didn't register the right group version
```
Comment (arschles) [inline pkg/storage/tpr/init_test.go]: @pmorie I'll go do a follow up right now

Comment (arschles) [inline pkg/storage/tpr/init_test.go]: @pmorie see https://github.com/kubernetes-incubator/service-catalog/pull/729
