### PR TITLE
Check only relevant resource APIs via discovery client at the controller-manager startup

### LINKED ISSUE #2418: Service Catalog controller-manager fails to start when unrelated API server is unavailable
# Bug Report 

**What happened**:
Service Catalog controller-manager is failing to start when some unrelated API server is down.
This is caused by a change https://github.com/kubernetes/kubernetes/pull/66932 that makes discovery return details about unavailable resources.
https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/controller-manager/app/controller_manager.go#L280-L283

**What you expected to happen**:
Service Catalog controller-manager should explicitly check availability of "servicecatalog.k8s.io" resources is failing to start when some unrelated API server is down.
We should fix the code to ignore errors in discovery unrelated to "servicecatalog.k8s.io" resource group.

**How to reproduce it (as minimally and precisely as possible)**:
Register a new `APIService` without starting an appropriate API server.
Deploy Service Catalog and see controller-manager being continuously restarted.

### PR DESCRIPTION
**Pull request by nilebox**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Make controller-manager not fail to startup when unrelated API server is down.

**Which issue(s) this PR fixes** 

Fixes #2418

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by nilebox** [comment]
Since this is mostly a follow-up fix for #2412, I will merge it without waiting for more approvals.
/lgtm
/approve

File: cmd/controller-manager/app/controller_manager.go [hunk 1]
```diff
@@ -306,15 +306,9 @@ func getAvailableResources(clientBuilder controller.ClientBuilder) (map[schema.G
...
-	allResources := map[schema.GroupVersionResource]bool{}
-	for _, apiResourceList := range resourceMap {
-		version, err := schema.ParseGroupVersion(apiResourceList.GroupVersion)
-		if err != nil {
-			return nil, err
-		}
-		for _, apiResource := range apiResourceList.APIResources {
-			allResources[version.WithResource(apiResource.Name)] = true
-		}
+	allResources := map[schema.GroupVersionResource]struct{}{}
```
Comment (ash2k) [inline cmd/controller-manager/app/controller_manager.go]: Could pre-allocate the map

File: cmd/controller-manager/app/controller_manager.go [hunk 2]
```diff
@@ -279,8 +279,8 @@ func Run(controllerManagerOptions *options.ControllerManagerServer) error {
 // getAvailableResources uses the discovery client to determine which API
 // groups are available in the endpoint reachable from the given client and
 // returns a map of them.
-func getAvailableResources(clientBuilder controller.ClientBuilder) (map[schema.GroupVersionResource]bool, error) {
-	var resourceMap []*metav1.APIResourceList
+func getAvailableResources(clientBuilder controller.ClientBuilder, version schema.GroupVersion) (map[schema.GroupVersionResource]struct{}, error) {
```
Comment (jberkhahn) [inline cmd/controller-manager/app/controller_manager.go]: I don't quite follow this. What do we get out of making it a map of void structs instead of bools? Other than that this looks good, but I don't see the reason for this change.

Comment (nilebox) [reply cmd/controller-manager/app/controller_manager.go]: @jberkhahn empty struct value is a recommended way of implementing a "set" structure using a map in Go. The difference with boolean is that empty struct doesn't take any space.
See https://www.davidkaya.sk/2017/12/10/sets-in-golang/ for example.

I agree that it's not a critical change, but for me it makes it clear that "this is a set, and value doesn't matter". We never put "false" in this map, so boolean is redundant.
